# Russian translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Emil <emil@emil-pc>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-04-26 14:17+0300\n"
"PO-Revision-Date: 2020-07-30 11:25+0300\n"
"Last-Translator: Emil <emil@emil-pc>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../common/migrations/versions/07972ddc0722_admin_user.py:53
msgid "Add new journal archive."
msgstr "Добавлен новый архив журнала."

#: ../common/migrations/versions/07972ddc0722_admin_user.py:54
msgid "Archive name:"
msgstr "Имя архива:"

#: ../common/migrations/versions/07972ddc0722_admin_user.py:55
msgid "path:"
msgstr "путь:"

#: ../common/models/active_tk_connection.py:127
msgid "Another task works on pool {} before creating new blank VM."
msgstr "Другая задача выполняется над пулом {} перед созданием новой пустой ВМ."

#: ../common/models/active_tk_connection.py:135
msgid "Expansion of guest pool {} requested."
msgstr "Запрошено расширение гостевого пула {}."

#: ../common/models/auth.py:209
msgid "Role {} is added to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:217 ../common/models/auth.py:243
msgid "User {} roles: {}."
msgstr "Роли пользователя {}: {}."

#: ../common/models/auth.py:222
msgid "Role {} is assigned to user {}."
msgstr "Роль {} назначена пользователю {}."

#: ../common/models/auth.py:233
msgid "Roles: {} was deleted to user {}."
msgstr "Роли: {} удалены у пользователя {}."

#: ../common/models/auth.py:291
msgid "User {} already has permission {}."
msgstr "Пользователь {} уже имеет разрешение."

#: ../common/models/auth.py:299
msgid "Permission(s) {} added to user {}."
msgstr "Разрешения {} назначены пользователю {}."

#: ../common/models/auth.py:322
msgid "Permission(s) {} removed from user {}."
msgstr "Разрешения {} удалены у пользователя {}."

#: ../common/models/auth.py:331
msgid "User {} permission(s): {}."
msgstr "Разрешения пользователя {}: {}."

#: ../common/models/auth.py:344
msgid "Group {} is removed for user {}."
msgstr "Группа {} удалена у пользователя {}."

#: ../common/models/auth.py:355
#, python-brace-format
msgid "User {username} has been activated."
msgstr "Пользователь {username} активирован."

#: ../common/models/auth.py:365
#, python-brace-format
msgid "User {username} has been activated on Astra."
msgstr "Пользователь {username} был активирован в системе."

#: ../common/models/auth.py:386
msgid "There is no more active superuser."
msgstr "Больше нет активного администратора."

#: ../common/models/auth.py:394
#, python-brace-format
msgid "User {username} has been deactivated."
msgstr "Пользователь {username} деактивирован."

#: ../common/models/auth.py:409
#, python-brace-format
msgid "User {username} has been deactivated on Astra."
msgstr "Пользователь {username} деактивирован в системе."

#: ../common/models/auth.py:461 ../common/models/auth.py:501
#, python-brace-format
msgid "Password of user {username} has been changed."
msgstr "Пароль пользователя {username} изменен."

#: ../common/models/auth.py:466
#, python-brace-format
msgid "Password of user {username} has`t been changed."
msgstr "Пароль пользователя {username} не был изменен."

#: ../common/models/auth.py:573
msgid "User {} password setting error."
msgstr "Ошибка задания пароля пользователя {}."

#: ../common/models/auth.py:585
msgid "User {} creation error."
msgstr "Ошибка создания пользователя {}."

#: ../common/models/auth.py:594
msgid "Superuser."
msgstr "Администратор."

#: ../common/models/auth.py:594
msgid "User."
msgstr "Пользователь."

#: ../common/models/auth.py:595
msgid "{} {} created."
msgstr "{} {} создан."

#: ../common/models/auth.py:646
msgid "User {} update error."
msgstr "Ошибка обновления пользователя {}."

#: ../common/models/auth.py:658
msgid "Values of user {} is changed."
msgstr "Параметры пользователя {} изменены."

#: ../common/models/auth.py:665 ../common/models/auth.py:676
msgid "Roles: {}."
msgstr "Роли: {}."

#: ../common/models/auth.py:666
#, python-brace-format
msgid "User {username} has become a superuser."
msgstr "Пользователь {username} стал администратором."

#: ../common/models/auth.py:677
#, python-brace-format
msgid "User {username} is no longer a superuser."
msgstr "Пользователь {username} перестал быть администратором."

#: ../common/models/auth.py:703
#, python-brace-format
msgid "User {username} has been logged in."
msgstr "Пользователь {username} вошел в систему."

#: ../common/models/auth.py:706
msgid "Auth type: {}, IP: {}."
msgstr "Тип авторизации: {}, IP: {}."

#: ../common/models/auth.py:727
#, python-brace-format
msgid "User {username} has been logged out."
msgstr "Пользователь {username} вышел из системы."

#: ../common/models/auth.py:853
msgid "Group {} is created."
msgstr "Группа {} создана."

#: ../common/models/auth.py:880
msgid "Group {} already has permission {}."
msgstr "Группа {} уже имеет разрешение {}."

#: ../common/models/auth.py:888
msgid "Permission(s) {} added to group {}."
msgstr "Разрешения: {} добавлены группе {}."

#: ../common/models/auth.py:911
msgid "Permission(s) {} removed from group {}."
msgstr "Разрешения {} удалены у группы {}."

#: ../common/models/auth.py:920
msgid "Group {} permission(s): {}."
msgstr "Разрешения группы {}: {}."

#: ../common/models/auth.py:938
msgid "Values of group {} is updated."
msgstr "Параметры группы {} обновлены."

#: ../common/models/auth.py:960
msgid "User {} has been included to group {}."
msgstr "Пользователь {} был включен в группу {}."

#: ../common/models/auth.py:967
msgid "User {} is already in group {}."
msgstr "Пользователь {} уже находится в группе {}."

#: ../common/models/auth.py:979
msgid "Removing user {} from group {}."
msgstr "Удаление пользователя {} из группы {}."

#: ../common/models/auth.py:992
msgid "Role {} has been set to group {}."
msgstr "Роль {} добавлена в группу {}."

#: ../common/models/auth.py:999
msgid "Group {} has already role {}."
msgstr "Группе {} уже назначена роль {}."

#: ../common/models/auth.py:1011
msgid "Roles: {} was deleted to group {}."
msgstr "Роли: {} удалены из группы {}."

#: ../common/models/authentication_directory.py:167
#: ../web_app/tests/test_auth_dir.py:155
msgid "More than one authentication directory can not be created."
msgstr "Не может быть создано более одной службы каталогов."

#: ../common/models/authentication_directory.py:195
msgid "Authentication directory {} is created."
msgstr "Служба каталогов {} создана."

#: ../common/models/authentication_directory.py:228
msgid "Values for auth directory is updated."
msgstr "Значения службы каталогов обновлены."

#: ../common/models/authentication_directory.py:263
msgid "Arguments: {} of group: {}."
msgstr "Аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:266
msgid "Mapping for auth directory {} is created."
msgstr "Сопоставление для службы каталогов {} создано."

#: ../common/models/authentication_directory.py:302
msgid "New arguments: {} of group: {}."
msgstr "Новые аргументы: {} группы: {}."

#: ../common/models/authentication_directory.py:305
msgid "Mapping for auth directory {} is updated."
msgstr "Mapping for auth directory {} is updated."

#: ../common/models/authentication_directory.py:331
#: ../common/models/authentication_directory.py:548
msgid "Authentication directory server {} is down."
msgstr "Сервер службы каталогов {} не работает."

#: ../common/models/authentication_directory.py:341
msgid "Authentication directory server {} is connected."
msgstr "Сервер службы каталогов {} подключен."

#: ../common/models/authentication_directory.py:380
msgid "Username must be a string."
msgstr "Имя пользователя должно быть строкой."

#: ../common/models/authentication_directory.py:413
msgid "Mappings: {}."
msgstr "Сопоставления: {}."

#: ../common/models/authentication_directory.py:431
msgid "escaped values: {}."
msgstr "скрытые значения: {}."

#: ../common/models/authentication_directory.py:433
msgid "role mapping value type: {}."
msgstr "тип значений отображения роли: {}."

#: ../common/models/authentication_directory.py:446
msgid "User VeiL groups: {}."
msgstr "Группы пользователей VeiL: {}."

#: ../common/models/authentication_directory.py:454
msgid "Attaching user {} to group: {}."
msgstr "Прикрепление пользователя {} к группе {}."

#: ../common/models/authentication_directory.py:474
#: ../common/models/authentication_directory.py:485
msgid "No authentication directory controllers."
msgstr "Нет контроллеров служб каталогов."

#: ../common/models/authentication_directory.py:509
msgid "Invalid credentials (ldap): {}."
msgstr "Неверные учетные данные (ldap): {}."

#: ../common/models/authentication_directory.py:516
msgid "Server down (ldap)."
msgstr "Сервер не отвечает (ldap)."

#: ../common/models/authentication_directory.py:533
msgid "LDAP username and password can`t be empty."
msgstr "Имя пользователя и пароль LDAP не могут быть пустыми."

#: ../common/models/authentication_directory.py:541
msgid "Authentication directory server {} has bad auth info."
msgstr "Не удалось подключиться к серверу службы каталогов {}."

#: ../common/models/authentication_directory.py:622
#: ../common/models/authentication_directory.py:711
msgid "Fail to connect to Authentication Directory. Check service information."
msgstr "Ошибка подключения к службе каталогов."

#: ../common/models/authentication_directory.py:768
msgid "{} new users synced from Authentication Directory."
msgstr "{} новых пользователей синхронизировано из службы каталогов."

#: ../common/models/authentication_directory.py:779
#: ../web_app/auth/group_schema.py:219
msgid "No such Group."
msgstr "Отсутствует такая группа."

#: ../common/models/authentication_directory.py:782
msgid "Group {} is not synchronized by AD."
msgstr "Группа {} не синхронизирована со службой каталогов."

#: ../common/models/authentication_directory.py:789
msgid "There is no users to sync."
msgstr "В группе не найдены пользователи для синхронизации."

#: ../common/models/controller.py:159
msgid "Controller {} has no api client."
msgstr "Контроллер {} не имеет подключения к ECP VeiL."

#: ../common/models/controller.py:165
msgid "ECP VeiL version could not be obtained. Check your token."
msgstr "Не удается получить версию ECP VeiL. Проверьте свой токен."

#: ../common/models/controller.py:173
msgid "ECP VeiL version should be 4.3 or higher. Current version is incompatible."
msgstr "Версия ECP VeiL должна быть 4.3 или выше. Текущая версия не поддерживается."

#: ../common/models/controller.py:205
msgid "Controller {} added."
msgstr "Контроллер {} добавлен."

#: ../common/models/controller.py:259
msgid "Controller {} has been successfully updated."
msgstr "Контроллер {} успешно обновлен."

#: ../common/models/controller.py:263
msgid "Controller {} update failed."
msgstr "Ошибка обновления контроллера {}."

#: ../common/models/controller.py:292
msgid "Controller {} has been removed."
msgstr "Контроллер {} удалён."

#: ../common/models/controller.py:323
msgid "Controller {} has been activated."
msgstr "Контроллер {} активирован."

#: ../common/models/controller.py:346 ../common/models/controller.py:373
msgid "Controller {} status has been switched to {}."
msgstr "Статус контроллера {} изменен на {}."

#: ../common/models/event.py:77
msgid "Journal in this period is empty."
msgstr "Журнал для этого периода пуст."

#: ../common/models/event.py:94
msgid "Path {} is incorrect."
msgstr "Неверный путь: {}."

#: ../common/models/event.py:97
msgid "Check date. Interval {} - {} is incorrect."
msgstr "Проверьте дату. Некорректный промежуток {} - {}."

#: ../common/models/event.py:102
msgid "Not enough free space."
msgstr "Недостаточно свободного места."

#: ../common/models/event.py:104
msgid "Journal export error."
msgstr "Ошибка экспорта журнала."

#: ../common/models/event.py:251
msgid "Choose right period."
msgstr "Выберите правильный период."

#: ../common/models/event.py:257
msgid "Count must be more than 1."
msgstr "Количество должно быть больше 1."

#: ../common/models/event.py:261
msgid "Journal settings changed."
msgstr "Настройки журнала изменены."

#: ../common/models/pool.py:234
msgid "Incorrect sorting option {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/models/pool.py:594
msgid "User {} has been included to pool {}."
msgstr "Пользователь {} был включен в пул {}."

#: ../common/models/pool.py:602 ../common/models/vm.py:244
msgid "{} already has permission."
msgstr "{} уже имеет разрешение."

#: ../common/models/pool.py:623
msgid "Removing user {} from pool {}."
msgstr "Удаление пользователя {} из пула {}."

#: ../common/models/pool.py:631
msgid "User {} has no direct right to pool {}."
msgstr "У пользователя {} нет прямых прав на пул {}. Пропускаем."

#: ../common/models/pool.py:659
msgid "Group {} has been included to pool {}."
msgstr "Группа {} включена в пул {}."

#: ../common/models/pool.py:667
msgid "Pool already has permission."
msgstr "Пул уже имеет разрешение."

#: ../common/models/pool.py:680
msgid "Removing group {} from pool {}."
msgstr "Удаление группы {} из пула {}."

#: ../common/models/pool.py:727
msgid "Controller {} not found."
msgstr "Контроллер {} не найден."

#: ../common/models/pool.py:755
msgid "Delete VMs for GuestPool {}."
msgstr "Удаление виртуальных машин для гостевого пула {}."

#: ../common/models/pool.py:759
msgid "Delete VMs for AutomatedPool {}."
msgstr "Удаление виртуальных машин для автоматического пула {}."

#: ../common/models/pool.py:765
msgid "VM {} has been removed from ECP VeiL."
msgstr "ВМ {} удалена  из ECP VeiL."

#: ../common/models/pool.py:779
#, python-brace-format
msgid "Complete removal pool of desktops {verbose_name} is done."
msgstr "Выполнено полное удаление пула рабочих столов {verbose_name}."

#: ../common/models/pool.py:810
msgid "Pool {} has been activated."
msgstr "Пул {} активирован."

#: ../common/models/pool.py:826
msgid "Pool {} status changed to {}."
msgstr "Статус пула {} изменен на {}."

#: ../common/models/pool.py:978
msgid "List of VM should not be empty."
msgstr "Список виртуальных машин не должен быть пустым."

#: ../common/models/pool.py:996
msgid "VM doesn't belong to specified pool."
msgstr "Виртуальная машина не принадлежит заданному пулу."

#: ../common/models/pool.py:1005
msgid "VM {} has been removed from the pool {} and ECP VeiL."
msgstr "ВМ {} удалена из пула {} и из ECP VeiL."

#: ../common/models/pool.py:1009
msgid "VM {} has been removed from the pool {}."
msgstr "ВМ {} удалена из пула {}."

#: ../common/models/pool.py:1081
#, python-brace-format
msgid "Tag {name} created for pool {name}."
msgstr "Тэг {name} добавлен к пулу {name}."

#: ../common/models/pool.py:1100
msgid "Tag {} removed from ECP VeiL."
msgstr "Тэг {} удален из ECP VeiL."

#: ../common/models/pool.py:1111
#, python-brace-format
msgid "Tag {name} updated for pool {name} and all vms in pool."
msgstr "Тэг {name} обновлен для пула {name} и всех ВМ в пуле."

#: ../common/models/pool.py:1138
msgid "Tag {} removed from VM {}."
msgstr "Тэг {} удален для ВМ {}."

#: ../common/models/pool.py:1153 ../common/models/pool.py:1170
msgid "Tag {} added to VM {}."
msgstr "Тэг {} назначен ВМ {}."

#: ../common/models/pool.py:1256 ../common/models/pool.py:1259
#: ../common/models/pool.py:1662
msgid "VM {} created."
msgstr "ВМ {} создана."

#: ../common/models/pool.py:1260 ../common/models/pool.py:1663
msgid "VM {} created and added to the pool {}."
msgstr "ВМ {} создана и добавлена в пул {}."

#: ../common/models/pool.py:1271
msgid "Static pool {} created."
msgstr "Статический пул {} создан."

#: ../common/models/pool.py:1293 ../common/models/pool.py:1527
msgid "Pool {} has been updated."
msgstr "Пул {} обновлен."

#: ../common/models/pool.py:1439
msgid "Initial_size: {}, total_size: {}, increase_step {}, reserve_size {}."
msgstr "Начальный размер: {}, Максимальный размер: {}, Шаг расширения: {}, Резервный размер: {}."

#: ../common/models/pool.py:1443
msgid "GuestPool {} is created."
msgstr "Создан гостевой пул {}."

#: ../common/models/pool.py:1450
msgid "AutomatedPool {} is created."
msgstr "Создан автоматический пул {}."

#: ../common/models/pool.py:1492 ../common/models/pool.py:1517
msgid "Update Pool {} values."
msgstr "Обновление значений пула {}."

#: ../common/models/pool.py:1572
msgid "There is no client for pool {}."
msgstr "Пул {} не имеет подключения к ECP VeiL. Проверьте контроллер."

#: ../common/models/pool.py:1604
msgid "VM creation task {} finished with error."
msgstr "Задача {} создания ВМ завершилась с ошибкой."

#: ../common/models/pool.py:1624
msgid "Fail to cancel VM creation task."
msgstr "Ошибка отмены задачи создания ВМ."

#: ../common/models/pool.py:1706
msgid "VM creation error."
msgstr "Ошибка создания ВМ."

#: ../common/models/pool.py:1711
msgid "{} vm(s) are successfully added in the {} pool."
msgstr "{} ВМ успешно добавлены в пул {}."

#: ../common/models/pool.py:1716
msgid "Adding VM to the pool {} finished with errors."
msgstr "Добавление ВМ в пул {} закончилось с ошибками."

#: ../common/models/pool.py:1719
msgid "Required: {}, created: {}."
msgstr "Необходимо: {}, создано: {}."

#: ../common/models/task.py:74
msgid "Creation of pool {}."
msgstr "Создание пула {}."

#: ../common/models/task.py:76
msgid "Expanding of pool {}."
msgstr "Расширение пула {}."

#: ../common/models/task.py:78
msgid "Deleting of pool {}."
msgstr "Удаление пула {}."

#: ../common/models/task.py:80
msgid "Decreasing of pool {}."
msgstr "Уменьшение пула {}."

#: ../common/models/task.py:82
msgid "Preparation of vm {}."
msgstr "Подготовка ВМ {}."

#: ../common/models/task.py:84
msgid "Backup of {}."
msgstr "Бэкап {}."

#: ../common/models/vm.py:152
msgid "Create VM {} on VDI DB."
msgstr "Создание виртуальной машины {} на VDI DB."

#: ../common/models/vm.py:184 ../web_app/thin_client_api/handlers.py:328
#: ../web_app/thin_client_api/handlers.py:358
msgid "VM has no api client."
msgstr "ВМ не имеет клиента. Проверьте состояние контроллера."

#: ../common/models/vm.py:195
msgid "VM deletion task {} finished with error."
msgstr "Задача {} удаления ВМ завершилась с ошибкой."

#: ../common/models/vm.py:200
msgid "VM {} removed from ECP."
msgstr "ВМ {} удалена из ECP."

#: ../common/models/vm.py:208
msgid "VM {} deletion task finished with error."
msgstr "Задача удаления ВМ {} завершилась с ошибкой."

#: ../common/models/vm.py:236
msgid "User {} has been included to VM {}."
msgstr "За пользователем {} закреплена ВМ {}."

#: ../common/models/vm.py:257 ../common/models/vm.py:697
msgid "VM {} is clear from users."
msgstr "ВМ {} освобождена от пользователей."

#: ../common/models/vm.py:298 ../common/models/vm.py:480
msgid "There is no client for controller {}."
msgstr "Контролер {} не имеет подключения к ECP VeiL."

#: ../common/models/vm.py:340
msgid "Not enough free space on data pool."
msgstr "Недостаточно свободного места в пуле данных."

#: ../common/models/vm.py:345
msgid "Possibly blocked by active task on ECP. Wait before next try."
msgstr "Возможно, заблокировано активным заданием на ECP. Подождите перед следующей попыткой."

#: ../common/models/vm.py:373
msgid "VM {} deleting cancelled by timeout."
msgstr "Удаление ВМ {} отменено по таймауту."

#: ../common/models/vm.py:411 ../web_app/controller/schema.py:481
#: ../web_app/journal/schema.py:294
msgid "No such event."
msgstr "Нет такого события."

#: ../common/models/vm.py:506
msgid "VM {} is powered."
msgstr "ВМ {} включена."

#: ../common/models/vm.py:518
msgid "VM can`t be powered on or already powered."
msgstr "ВМ не включается или уже включена."

#: ../common/models/vm.py:525
msgid "VM {} already shutdown."
msgstr "ВМ {} уже выключена."

#: ../common/models/vm.py:534
msgid "VM {} is force shutdown."
msgstr "ВМ {} принудительно выключена."

#: ../common/models/vm.py:540
msgid "VM {} is shutdown."
msgstr "ВМ {} выключена."

#: ../common/models/vm.py:551 ../common/models/vm.py:586
#: ../web_app/pool/schema.py:218 ../web_app/pool/schema.py:234
msgid "VM {} is shutdown. Please power this."
msgstr "ВМ {} выключена. Пожалуйста включите её."

#: ../common/models/vm.py:561
msgid "VM {} was force reboot."
msgstr "ВМ {} принудительно перезагружена."

#: ../common/models/vm.py:567
msgid "VM {} was reboot."
msgstr "ВМ {} перезагружена."

#: ../common/models/vm.py:579
msgid "VM {} is suspended."
msgstr "ВМ {} приостановлена."

#: ../common/models/vm.py:598
msgid "Forbid create backup from a thin clone: {}."
msgstr "Запрещено создание резервной копии от тонкого клона: {}."

#: ../common/models/vm.py:609 ../pool_worker/pool_tasks.py:460
msgid "Creating backup finished with error."
msgstr "Создание резервной копии завершилось с ошибкой."

#: ../common/models/vm.py:612
msgid "Backup for VM {} is created."
msgstr "Создана резервная копия для ВМ {}."

#: ../common/models/vm.py:663
msgid "Total size of pool {} increased."
msgstr "Увеличен максимальный размер пула {}."

#: ../common/models/vm.py:675 ../web_app/pool/schema.py:825
msgid "VM {} has been added to the pool {}."
msgstr "ВМ {} добавлена в пул {}."

#: ../common/models/vm.py:707
msgid "Backup restore finished with error."
msgstr "Восстановление из резервной копии завершилось с ошибкой."

#: ../common/models/vm.py:710
msgid "Backup from VM {} restored to pool {} as {}."
msgstr "Резервная копия для ВМ {} восстановлена в пул {} с именем {}."

#: ../common/models/vm.py:734
msgid "VM {} remote access enabled."
msgstr "Удаленный доступ ВМ {} включен."

#: ../common/models/vm.py:758
msgid "Can`t set verbose name."
msgstr "Can`t set verbose name."

#: ../common/models/vm.py:791
msgid "VM {} hostname setting task failed."
msgstr "Ошибка задания hostname ВМ {}."

#: ../common/models/vm.py:795
msgid "VM {} hostname setting success."
msgstr "ВМ {} успешно задан hostname."

#: ../common/models/vm.py:819
msgid "Active directory object has no service username or password. Including skipped."
msgstr "У службы каталогов не указаны имя пользователя и пароль. Пропускаем."

#: ../common/models/vm.py:851
msgid "VM {} active directory group including error."
msgstr "Ошибка ввода ВМ {} в группу AD."

#: ../common/models/vm.py:860
msgid "VM {} AD group including successful."
msgstr "ВМ {} успешно заведена в контейнер/группу AD."

#: ../common/models/vm.py:884
msgid "VM {} failed to receive DHCP ip address ({})."
msgstr "VM {} не удалось получить IP адрес по DHCP ({})."

#: ../common/models/vm.py:903
msgid "VM {} domain including task failed."
msgstr "Ошибка включения ВМ {} в домен."

#: ../common/models/vm.py:905
msgid "VM {} AD inclusion success."
msgstr "ВМ {} успешно заведена в AD."

#: ../common/models/vm.py:908
msgid "VM {} AD inclusion skipped."
msgstr "Заведение ВМ {} в домен пропущено."

#: ../common/models/vm.py:931
msgid "VM {} has been prepared."
msgstr "ВМ {} подготовлена."

#: ../common/models/vm.py:948
msgid "{} preparation cancelled by timeout."
msgstr "подготовка {} отменена по таймауту."

#: ../common/models/vm.py:959
msgid "VM {} preparation error."
msgstr "Ошибка подготовки ВМ {}."

#: ../common/veil/auth/veil_jwt.py:34
msgid "Token invalid."
msgstr "Недействительный токен."

#: ../common/veil/auth/veil_jwt.py:39
msgid "Token expired."
msgstr "Срок действия токена истек."

#: ../common/veil/auth/veil_jwt.py:96
msgid "Error with JWT decode."
msgstr "Ошибка JWT декодирования."

#: ../common/veil/auth/veil_jwt.py:106 ../common/veil/auth/veil_jwt.py:108
#: ../common/veil/auth/veil_jwt.py:110
msgid "Invalid authorization header."
msgstr "Неправильный заголовок авторизации."

#: ../common/veil/auth/veil_jwt.py:114
msgid "Missing authorization header."
msgstr "Пропущен заголовок авторизации."

#: ../common/veil/veil_api.py:148
msgid "Can`t find VM {} on VeiL ECP."
msgstr "Не удалось найти ВМ {} на VeiL ECP."

#: ../common/veil/veil_api.py:158
msgid "Can`t find Tag {} on VeiL ECP."
msgstr "Не удалось найти Тег {} на VeiL ECP."

#: ../common/veil/veil_api.py:180
msgid "VeiL ECP {} request error."
msgstr "Ошибка запроса ECP VeiL {}."

#: ../common/veil/veil_decorators.py:44 ../common/veil/veil_decorators.py:50
#: ../web_app/auth/license/handlers.py:37 ../web_app/tests/test_auth_v2.py:115
msgid "Invalid permissions."
msgstr "Недостаточно прав."

#: ../common/veil/veil_decorators.py:45
msgid "IP: {}. username: {}."
msgstr "IP: {}. Пользователь: {}."

#: ../common/veil/veil_errors.py:158
msgid "Unable to logon to system using these credentials."
msgstr "Не удалось войти в систему с предоставленными учетными данными."

#: ../common/veil/veil_errors.py:163
msgid "401: Unauthorized."
msgstr "Ошибка 401: проблема с авторизацией."

#: ../common/veil/veil_gino.py:84
msgid "Incorrect sort parameter {}."
msgstr "Неверный параметр сортировки {}."

#: ../common/veil/veil_gino.py:95
msgid "Incorrect request parameter {}."
msgstr "Неверный параметр запроса {}."

#: ../common/veil/veil_gino.py:223
msgid "{} {} has been disabled."
msgstr "{} {} деактивирована."

#: ../common/veil/veil_gino.py:225
msgid "{} {} has`t been found in ECP VeiL. Switched to FAILED."
msgstr "{} {} не найдена на ECP VeiL. Переключена в стутус FAILED."

#: ../common/veil/veil_gino.py:237
msgid "Soft_delete exception: {}."
msgstr "Ошибка удаления: {}."

#: ../common/veil/veil_handlers.py:54 ../common/veil/veil_handlers.py:97
msgid "User {} not found."
msgstr "Пользователь {} не найден."

#: ../common/veil/veil_handlers.py:101
msgid "There is no pool with id: {}."
msgstr "Отсутствует пул с ID: {}."

#: ../common/veil/veil_handlers.py:105
msgid "User {} has no VM on pool {}."
msgstr "У пользователя {} нет виртуальной машины в пуле {}."

#: ../common/veil/veil_handlers.py:183
msgid "Ws write error."
msgstr "Ошибка записи WS."

#: ../common/veil/veil_redis.py:153
msgid "Redis waiting exception."
msgstr "Ошибка Redis."

#: ../common/veil/veil_redis.py:214
msgid "Redis task waiting exception."
msgstr "Ошибка redis-задачи."

#: ../common/veil/veil_validators.py:34
msgid "Field \"{}\" - {}."
msgstr "Поле \"{}\" - {}."

#: ../pool_worker/pool_task_manager.py:74
msgid "Can`t launch task."
msgstr "Нет такого задания."

#: ../pool_worker/pool_tasks.py:77
msgid "Task '{}' started."
msgstr "Задача '{}' начала выполнение."

#: ../pool_worker/pool_tasks.py:86
msgid "Task '{}' finished successfully."
msgstr "Задача '{}' завершилась успешно."

#: ../pool_worker/pool_tasks.py:92
msgid "Task '{}' cancelled."
msgstr "Задача '{}' отменена."

#: ../pool_worker/pool_tasks.py:98
msgid "Task '{}' failed."
msgstr "Задача '{}' завершилась с ошибками."

#: ../pool_worker/pool_tasks.py:159
msgid "Pool Creation cancelled."
msgstr "Создание пула отменено."

#: ../pool_worker/pool_tasks.py:164
msgid "Failed to init pool."
msgstr "Ошибка инициализации пула."

#: ../pool_worker/pool_tasks.py:184
msgid "Pool initialization VM(s) preparation error."
msgstr "В момент инициализации пула подготовка виртуальных машин завершилась с ошибкой."

#: ../pool_worker/pool_tasks.py:255
msgid "VM creating error."
msgstr "Ошибка создания ВМ."

#: ../pool_worker/pool_tasks.py:277
msgid "VM preparation error."
msgstr "Ошибка подготовки ВМ."

#: ../pool_worker/pool_tasks.py:371
msgid "Another task works on this VM."
msgstr "ВМ заблокирована выполнением другой задачи."

#: ../pool_worker/pool_tasks.py:414
msgid "ECP VeiL domain request error."
msgstr "Ошибка запроса ECP VeiL ВМ."

#: ../pool_worker/pool_tasks.py:417
msgid "Task has`t been created."
msgstr "Задача не была создана."

#: ../pool_worker/pool_tasks.py:431
msgid "VM remote access task {} finished with error."
msgstr "Задача {} включения удаленного доступа ВМ завершилась с ошибкой."

#: ../pool_worker/pool_tasks.py:457
msgid "Wrong entity type."
msgstr "Неверный тип сущности."

#: ../pool_worker/vm_manager.py:105
msgid "Keep vms on task error."
msgstr "Сохранить ВМ при ошибке задачи."

#: ../pool_worker/vm_manager.py:149
msgid "Synchronize vm data task error."
msgstr "Ошибка задачи синхронизации данных виртуальной машины."

#: ../web_app/app.py:119
msgid "VDI broker stopped."
msgstr "VDI брокер остановлен."

#: ../web_app/app.py:130
msgid "VDI broker started with {} worker(s)."
msgstr "VDI брокер запущен в {} экземпляре(ах)."

#: ../web_app/app.py:134
msgid "Authentication system is disabled."
msgstr "Система аутентификации выключена."

#: ../web_app/app.py:138
msgid "The license is expired. Some functions will be blocked. Contact your dealer."
msgstr "Лицензия истекла. Некоторые функции будут заблокированы. Свяжитесь с вашим поставщиком."

#: ../web_app/app.py:142
msgid "DEBUG mode is enabled."
msgstr "Режим отладки включен."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:33
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:231
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:295
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:466
#: ../web_app/auth/authentication_directory/auth_dir_schema.py:484
msgid "No such Authentication Directory."
msgstr "Такая Authentication Directory отсутствует."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:39
msgid "Authentication directory URL should start with ldap(s)://."
msgstr "Ссылка на службу каталогов должна начинаться с ldap(s)://."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:46
msgid "Verbose name should not be empty."
msgstr "Имя verbose не должно быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:53
msgid "Value should be 1-63 latin characters, -, . or _."
msgstr "Значение должно быть в диапазоне от 1-63 латинских символа, -, . или _."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:74
#: ../web_app/auth/group_schema.py:49
msgid "users count not much with db count."
msgstr "Счетчик пользователей не коррелирует с счетчиком БД."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:76
msgid "groups list is empty."
msgstr "Список групп пуст."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:83
msgid "No such mapping."
msgstr "Нет такого отображения."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:88
msgid "DC should not be empty."
msgstr "Класс объекта домена не должен быть пустым."

#: ../web_app/auth/authentication_directory/auth_dir_schema.py:227
msgid "Specify id."
msgstr "Укажите ID."

#: ../web_app/auth/group_schema.py:27 ../web_app/auth/group_schema.py:145
msgid "No such group."
msgstr "Отсутствует такая группа."

#: ../web_app/auth/group_schema.py:35
msgid "verbose name must me <= 128 characters."
msgstr "имя должно быть <= 128 символов."

#: ../web_app/auth/group_schema.py:36
msgid "verbose_name is empty."
msgstr "имя пустое."

#: ../web_app/auth/group_schema.py:51
msgid "users list is empty."
msgstr "список пользователей пуст."

#: ../web_app/auth/group_schema.py:56
msgid "Last name length must be <= 255 characters."
msgstr "Фамилия должна быть <= 255 символам."

#: ../web_app/auth/group_schema.py:209
msgid "Specify Group.id or Group.ad_guid."
msgstr "Укажите Group.id или Group.ad_guid."

#: ../web_app/auth/group_schema.py:211
msgid "Specify Group.id or Group.ad_guid. Not both."
msgstr "Укажите Group.id или Group.ad_guid. Не оба."

#: ../web_app/auth/handlers.py:24
msgid "Missing request body."
msgstr "Отсутствует тело запроса."

#: ../web_app/auth/handlers.py:26
msgid "Missing username and password."
msgstr "Отсутствует имя пользователя и пароль."

#: ../web_app/auth/handlers.py:31
msgid "Missing username."
msgstr "Отсутствует имя пользователя."

#: ../web_app/auth/handlers.py:33
msgid "Missing password."
msgstr "Отсутствует пароль."

#: ../web_app/auth/handlers.py:45
msgid "External auth system is disabled. Check broker settings."
msgstr "Внешняя служба авторизации отключена. Проверьте настройки брокера."

#: ../web_app/auth/handlers.py:49
msgid "PAM or LOCAL auth only. Check broker settings."
msgstr "Проверьте настройки брокера. Разрешена только pam ИЛИ локальная авторизация."

#: ../web_app/auth/handlers.py:56
msgid "Invalid credentials."
msgstr "Неверные учетные данные."

#: ../web_app/auth/handlers.py:59
msgid "Auth system is disabled. Check broker settings."
msgstr "Проверьте настройки брокера. Система аутентификации отключена."

#: ../web_app/auth/handlers.py:74
msgid "Authentication failed for user: {}."
msgstr "Ошибка авторизации пользователя: {}."

#: ../web_app/auth/handlers.py:91
msgid "User {} logged out."
msgstr "Пользователь {} вышел из системы."

#: ../web_app/auth/handlers.py:101
msgid "Demo version."
msgstr "Демонстрационная версия."

#: ../web_app/auth/license/handlers.py:52
msgid "Bad extension."
msgstr "Недопустимое расширение."

#: ../web_app/auth/license/handlers.py:63
msgid "Fail to open license key file."
msgstr "Не удалось открыть лицензионный ключ."

#: ../web_app/auth/license/handlers.py:70
msgid "Try to upload invalid license key."
msgstr "Неудачная попытка загрузить лицензионный ключ."

#: ../web_app/auth/license/handlers.py:73
msgid "Valid license key is uploaded."
msgstr "Лицензионный ключ загружен."

#: ../web_app/auth/user_schema.py:32 ../web_app/auth/user_schema.py:242
#: ../web_app/thin_client_api/schema.py:308
msgid "No such user."
msgstr "Нет такого пользователя."

#: ../web_app/auth/user_schema.py:43
msgid "username must contain >= 3 chars (letters, digits, _, -, +) and can't contain any spaces."
msgstr "имя пользователя должно быть >= 3 символов (буквы, цифры, _, -, +) и не содержать пробелов."

#: ../web_app/auth/user_schema.py:52
msgid "Email {} is already busy."
msgstr "Email {} занят."

#: ../web_app/auth/user_schema.py:64
msgid "Email must contain English characters and/or digits, @ and domain name."
msgstr "Email должен содержать символы латинского алфавита и/или цифры, иметь @ и домен."

#: ../web_app/auth/user_schema.py:80
msgid "First name length must be <= 32 characters."
msgstr "Имя должно быть <= 32 символов."

#: ../web_app/auth/user_schema.py:86
msgid "Last name length must be <= 128 characters."
msgstr "Фамилия должна быть <= 128 символам."

#: ../web_app/auth/user_schema.py:238
msgid "Specify id or username."
msgstr "Укажите ID или имя пользователя."

#: ../web_app/auth/user_schema.py:457
msgid "Can`t remove permission(s) {} because they are granted to groups of user {}."
msgstr "Невозможно удалить разрешения {}, так как они выданы группам, в которых состоит пользователь."

#: ../web_app/controller/resource_schema.py:349
msgid "{} is unreachable on ECP VeiL."
msgstr "{} недоступен на ECP VeiL."

#: ../web_app/controller/resource_schema.py:562 ../web_app/pool/schema.py:1516
msgid "Cant create CD-ROM for powered domain {}."
msgstr "Невозможно создать CD-ROM для включенной виртуальной машины {}."

#: ../web_app/controller/resource_schema.py:570 ../web_app/pool/schema.py:1524
msgid "Creating a CD-ROM on the virtual machine {}."
msgstr "Создание CD-ROM на виртуальной машине {}."

#: ../web_app/controller/schema.py:31
msgid "name can`t be empty."
msgstr "имя не может быть пустым."

#: ../web_app/controller/schema.py:41
msgid "name `{}` is busy."
msgstr "имя `{}` уже используется."

#: ../web_app/controller/schema.py:49
msgid "address can`t be empty."
msgstr "адресс не может быть пустым."

#: ../web_app/controller/schema.py:59
msgid "address `{}` is busy."
msgstr "адресс `{}` уже используется."

#: ../web_app/controller/schema.py:66
msgid "token can`t be empty."
msgstr "токен не может быть пустым."

#: ../web_app/controller/schema.py:77 ../web_app/pool/schema.py:64
msgid "No such controller."
msgstr "Нет такого контроллера."

#: ../web_app/controller/schema.py:521 ../web_app/controller/schema.py:554
msgid "Connection to ECP has been failed."
msgstr "Соединение с ECP не удалось."

#: ../web_app/front_ws_api/handlers.py:50
msgid "WebSocket opened."
msgstr "WebSocket открыт."

#: ../web_app/front_ws_api/handlers.py:55
msgid "Message: {}."
msgstr "Сообщение: {}."

#: ../web_app/front_ws_api/handlers.py:79
msgid "WS listener error."
msgstr "Ошибка сервиса прослушивания WS."

#: ../web_app/front_ws_api/handlers.py:80
msgid "Unknown subscription source."
msgstr "Неизвестный источник подписки."

#: ../web_app/front_ws_api/handlers.py:97
msgid "Already subscribed."
msgstr "Уже подписан."

#: ../web_app/front_ws_api/handlers.py:104
msgid "Not subscribed."
msgstr "Не подписан."

#: ../web_app/journal/schema.py:272
msgid "The sort parameter is incorrect."
msgstr "Неверный параметр сортировки."

#: ../web_app/journal/schema.py:414
msgid "Journal is exported."
msgstr "Журнал экспортирован."

#: ../web_app/pool/schema.py:217
msgid "Missing connection spice data."
msgstr "Пропущены данные для spice соединения."

#: ../web_app/pool/schema.py:233
msgid "Missing connection vnc data."
msgstr "Пропущены данные для vnc соединения."

#: ../web_app/pool/schema.py:255 ../web_app/pool/schema.py:645
#: ../web_app/pool/schema.py:666
msgid "No such pool."
msgstr "Нет такого пула."

#: ../web_app/pool/schema.py:266
msgid "Pool name must contain only characters, digits, _, -."
msgstr "Имя пула должно содержать только буквы, цифры и -."

#: ../web_app/pool/schema.py:282
msgid "Template name of VM must contain only characters, digits, -. Template name length must be in [{} {}] interval."
msgstr "Шаблонное имя вм должно содержать только буквы, цифры, -. Длина шаблонного имени должна быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:293
msgid "Initial number of VM must be in {}-{} interval."
msgstr "Начальное число виртуальных машин должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:317
msgid "Reserve size of VMs can not be more than maximal number of Vms."
msgstr "Резервное число ВМ не может быть больше максимального числа ВМ."

#: ../web_app/pool/schema.py:322
msgid "Reserve size of VM must be in {}-{} interval."
msgstr "Резервное число ВМ должно быть в интервале {}-{}."

#: ../web_app/pool/schema.py:351
msgid "Maximal number of created VM can not be less than initial number of VM."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше начального числа ВМ."

#: ../web_app/pool/schema.py:356
msgid "Maximal number of created VM must be in [{} {}] interval."
msgstr "Максимальное число создаваемых виртуальных машин должно быть в интервале [{} {}]."

#: ../web_app/pool/schema.py:363
msgid "Maximal number of created VMs can not be less than current amount of Vms."
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше текущего числа ВМ."

#: ../web_app/pool/schema.py:381
msgid "Increase step must be positive and less or equal to total_size."
msgstr "Шаг увеличения должен быть положительным и меньше или равен общему количеству."

#: ../web_app/pool/schema.py:388
msgid "Connection type cannot be empty."
msgstr "Тип подключения не может быть пустым."

#: ../web_app/pool/schema.py:534 ../web_app/thin_client_api/handlers.py:180
msgid "VM is unreachable on ECP VeiL."
msgstr "ВМ недоступна на ECP VeiL."

#: ../web_app/pool/schema.py:693
msgid "Pool {} has been restored."
msgstr "Ошибки пула {} сброшены."

#: ../web_app/pool/schema.py:698
msgid "Pool {} is in service mode."
msgstr "Пул {} находится в сервисном режиме."

#: ../web_app/pool/schema.py:701
msgid "Pool {} is already active."
msgstr "Пул {} уже активирован."

#: ../web_app/pool/schema.py:772
msgid "Failed to create static pool {}."
msgstr "Ошибка создания статического пула {}."

#: ../web_app/pool/schema.py:808
msgid "VM {} is already in one of pools."
msgstr "Виртуальная машина {} уже в одном из пулов."

#: ../web_app/pool/schema.py:886
msgid "Failed to update static pool {}. Name must be unique."
msgstr "Ошибка редактирования статического пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:919
msgid "Can not expand pool {} because it reached its total_size."
msgstr "Не удается расширить пул {} т.к. достигнут максимальный размер."

#: ../web_app/pool/schema.py:929
msgid "Another task works on pool {}."
msgstr "Другая задача выполняется над пулом {}."

#: ../web_app/pool/schema.py:936
msgid "Increase_step {}."
msgstr "Шаг расширения пула {}."

#: ../web_app/pool/schema.py:938
msgid "Expansion of pool {} requested."
msgstr "Запрошено расширение пула {}."

#: ../web_app/pool/schema.py:1031
msgid "Failed to create pool {}."
msgstr "Ошибка создания пула {}."

#: ../web_app/pool/schema.py:1120
msgid "Failed to update pool {}. Name must be unique."
msgstr "Ошибка редактирования пула {}. Имя должно быть уникальным."

#: ../web_app/pool/schema.py:1255
msgid "There is no VM {}."
msgstr "Нет ВМ {}."

#: ../web_app/pool/schema.py:1273
msgid "User does not have the right to use pool, which has VM."
msgstr "У пользователя нет прав на использование пула, которому принадлежит ВМ."

#: ../web_app/pool/schema.py:1317
msgid "Another task works on VM {}."
msgstr "Другая задача выполняется над ВМ {}."

#: ../web_app/pool/schema.py:1469
msgid "Only VM with Windows OS can be in domain."
msgstr "Только ВМ на ОС Windows могут находиться в домене."

#: ../web_app/pool/schema.py:1546
msgid "VM {} is powered. Please shutdown this."
msgstr "ВМ {} включена. Пожалуйста выключите её."

#: ../web_app/pool/schema.py:1551
msgid "VeiL ECP error: {}."
msgstr "Ошибка запроса ECP VeiL: {}."

#: ../web_app/pool/schema.py:1554
msgid "The template {} change and distribute this changes to thin clones."
msgstr "Шаблон {} изменен и распространен с изменениями на тонкие клоны."

#: ../web_app/task/schema.py:101
msgid "No such task."
msgstr "Нет такого задания."

#: ../web_app/task/schema.py:138
msgid "No such task or status of task {} is not {}."
msgstr "Нет такого задания или статус задания {} не {}."

#: ../web_app/thin_client_api/handlers.py:78
msgid "User {} requested pools data."
msgstr "Пользователь {} запросил список пулов."

#: ../web_app/thin_client_api/handlers.py:102
msgid "Thin client limit exceeded."
msgstr "Превышен лимит тонких клиентов."

#: ../web_app/thin_client_api/handlers.py:109
msgid "Pool not found."
msgstr "Пул не найден."

#: ../web_app/thin_client_api/handlers.py:119
msgid "The pool doesnt support connection type {}."
msgstr "Пул не поддерживает тип соединения {}."

#: ../web_app/thin_client_api/handlers.py:147
msgid "The pool doesn`t have free machines. Try again after 5 minutes."
msgstr "В пуле нет свободных машин. Повторите попытку через 5 минут."

#: ../web_app/thin_client_api/handlers.py:159
msgid "The pool doesn`t have free machines."
msgstr "В пуле нет свободных машин."

#: ../web_app/thin_client_api/handlers.py:188
msgid "User {} connected to pool {}."
msgstr "Пользователь {} подключился к пулу {}."

#: ../web_app/thin_client_api/handlers.py:193
msgid "User {} connected to VM {}."
msgstr "Пользователь {} подключился к ВМ {}."

#: ../web_app/thin_client_api/handlers.py:205
msgid "The remote controller is unavailable."
msgstr "Контроллер недоступен."

#: ../web_app/thin_client_api/handlers.py:225
msgid "VM does not support RDP. The controller didn`t provide a VM address."
msgstr "Виртуальная машина не поддерживает RDP. Контроллер не передал адрес ВМ."

#: ../web_app/thin_client_api/handlers.py:295
msgid "User {} executed action {} on VM {}."
msgstr "Пользователь {} выполнил действие {} над ВМ {}."

#: ../web_app/thin_client_api/handlers.py:297
msgid "User {} failed to execute action {} on VM {}."
msgstr "Пользователю {} не удалось выполнить действие {} над ВМ {}."

#: ../web_app/thin_client_api/handlers.py:382
msgid "Message can not be empty."
msgstr "Сообщение не может быть пустым."

#: ../web_app/thin_client_api/handlers.py:403
msgid "Wrong message format."
msgstr "Неправильны формат сообщения."

#: ../web_app/thin_client_api/schema.py:299
msgid "All connections."
msgstr "Все подключения."

#: ../web_app/thin_client_api/schema.py:302
msgid "Connection id: {}."
msgstr "ID подключения: {}."

#: ../web_app/thin_client_api/schema.py:309
msgid "Connections of user: {}."
msgstr "Подключения пользователя {}."

#: ../web_app/thin_client_api/schema.py:313
msgid "Thin client disconnect requested."
msgstr "Запрошено отключение тонкого клиента."

#: ../web_app/thin_client_api/schema.py:349
msgid "User {} does not exist."
msgstr "Не существует пользователя {}."

#: ../ws_listener_worker/resources_monitor.py:105
msgid "{} is connected: {}."
msgstr "{} подключен: {}."

#: ../ws_listener_worker/resources_monitor.py:165
msgid "Resource monitor can`t connect to controller {}."
msgstr "Монитор ресурсов не может подключиться к контроллеру {}."

#: ../ws_listener_worker/resources_monitor.py:194
msgid "Closing ws connection {}."
msgstr "Закрываем WS соединение {}."

#: ../ws_listener_worker/resources_monitor_manager.py:62
#, python-brace-format
msgid "{cls}: connected controllers -- {controllers}."
msgstr "{cls}: подключенные контроллеры -- {controllers}."

#: ../ws_listener_worker/resources_monitor_manager.py:73
msgid "{}: Started."
msgstr "{}: Запущен."

#: ../ws_listener_worker/resources_monitor_manager.py:89
#, python-brace-format
msgid "{cls}: Controller {name} is already monitored."
msgstr "{cls}: Контроллер {name} уже отслеживается."

#: ../ws_listener_worker/resources_monitor_manager.py:96
#, python-brace-format
msgid "{cls}: resource monitor for controller {name} connected."
msgstr "{cls}: монитор ресурсов для контроллера {name} подключен."

#~ msgid "Update Pool values for AutomatedPool {}."
#~ msgstr "Обновление значений пула для автоматического пула {}."

#~ msgid "Failed to create automated pool {}."
#~ msgstr "Ошибка создания автоматического пула {}."

#~ msgid "Failed to update automated pool {}. Name must be unique."
#~ msgstr "Ошибка редактирования автоматического пула {}. Имя должно быть уникальным."

#~ msgid "ECP VeiL controller {} error."
#~ msgstr "Ошибка контроллера ECP VeiL {}."

#~ msgid "Critical controller error."
#~ msgstr "Критическая ошибка контроллера."

#~ msgid "Role {} has been set to pool {}."
#~ msgstr "Роль {} добавлена в пул {}."

#~ msgid "Pool already has role."
#~ msgstr "Пул уже имеет роль."

#~ msgid "Roles: {} was deleted to pool {}."
#~ msgstr "Роли: {} удалены в пуле {}."

#~ msgid "Controller can`t create VM. Unknown node."
#~ msgstr "Контроллер не может создать ВМ. Неизвестный узел."

#~ msgid "Unknown node {}."
#~ msgstr "Неизвестный узел {}."

#~ msgid "Attempts to create VM {} have been exhausted."
#~ msgstr "Превышен лимит попыток создания ВМ {}."

#~ msgid "  Duration: {}."
#~ msgstr "  Продолжительность: {}."

#~ msgid "User {} created with role {}."
#~ msgstr "Пользователь {} создан с ролью {}."

#~ msgid "Something went wrong. Interrupt while."
#~ msgstr "Что-то пошло не так. Прерываем while."

#~ msgid "Controller has not free space for creating new VM."
#~ msgstr "На контроллере отсутствует место для создания новой виртуальной машины."

#~ msgid "Pool {} has been deactivated."
#~ msgstr "Пул {} деактивирован."

#~ msgid "Can`t connect to {}."
#~ msgstr "Не удается подключиться к {}."

#~ msgid "StaticPool: Create VMs."
#~ msgstr "Статический пул: создание виртуальных машин."

#~ msgid "StaticPool: Create StaticPool."
#~ msgstr "Статический пул: создание статического пула."

#~ msgid "StaticPool: Create Pool."
#~ msgstr "Статический пул: создание пула."
