# Russian translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Emil <e.gareev@mashtab.org>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-05-20 12:26+0300\n"
"PO-Revision-Date: 2020-03-16 17:13+0300\n"
"Last-Translator: Emil <e.gareev@mashtab.org>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: app.py:111
msgid "Stopping Tornado VDI"
msgstr "Остановка Tornado VDI"

#: app.py:113
msgid "Stopping redis"
msgstr "Остановка redis"

#: app.py:116
msgid "Stopping resources_monitor_manager"
msgstr "Остановка менеджера мониторинга ресурсов"

#: app.py:119
msgid "Stopping GINO"
msgstr "Остановка GINO"

#: app.py:122
msgid "Stopping IOLoop"
msgstr "Остановка IOLoop"

#: app.py:125
msgid "Tornado VDI stopped"
msgstr "Tornado VDI остановлен"

#: app.py:138
msgid "Tornado VDI started"
msgstr "Tornado VDI запущен"

#: app.py:141
msgid "Auth is disabled. Enable on production!"
msgstr "Используйте выключенную авторизацию только в режиме отладки!"

#: app.py:145
msgid "The license is expired. Some functions will be blocked. Contact your dealer."
msgstr "Лицензия истекла. Некоторые функции будут недоступны."

#: app.py:147
msgid "License status: {}, expiration time: {}, thin clients limit: {}"
msgstr "Статус лицензии: {}, дата истечения: {}, лимит тонких клиентов: {}"

#: auth/authentication_directory/auth_dir_schema.py:31
#: auth/authentication_directory/auth_dir_schema.py:170
msgid "No such Authentication Directory."
msgstr "Отсутствует такая директория авторизации."

#: auth/authentication_directory/auth_dir_schema.py:37
msgid "Authentication directory URL should start with ldap(s)://."
msgstr "Ссылка на директорию авторизации должна начинаться с ldap(s)://."

#: auth/authentication_directory/auth_dir_schema.py:44
msgid "Verbose name should not be empty."
msgstr "Имя verbose не должно быть пустым."

#: auth/authentication_directory/auth_dir_schema.py:52
msgid "'domain name' should be a string split by a dot."
msgstr ""

#: auth/authentication_directory/auth_dir_schema.py:67 auth/group_schema.py:44
msgid "users count not much with db count."
msgstr "Счетчик пользователей не коррелирует с счетчиком БД."

#: auth/authentication_directory/auth_dir_schema.py:69
msgid "groups list is empty."
msgstr "Список групп пуст."

#: auth/authentication_directory/auth_dir_schema.py:76
msgid "No such mapping."
msgstr "Нет такого отображения."

#: auth/authentication_directory/auth_dir_schema.py:166
msgid "Specify id."
msgstr "Укажите ID."

#: auth/authentication_directory/auth_dir_schema.py:224
msgid "Authentication directory"
msgstr "Директория авторизации"

#: auth/authentication_directory/auth_dir_schema.py:328
msgid "In authentication directory {} mapping"
msgstr "В директории авторизации {} отображение"

#: auth/authentication_directory/models.py:126 tests/test_auth_dir_v2.py:65
msgid "More than one authentication directory can not be created."
msgstr "Не может быть создано более одной директории авторизации."

#: auth/authentication_directory/models.py:147
msgid "Authentication directory {} is created"
msgstr "Директория авторизации {} создана"

#: auth/authentication_directory/models.py:187
msgid "Id: {}. Arguments: {}"
msgstr "Id: {}. Аргументы: {}"

#: auth/authentication_directory/models.py:188
msgid "Values for auth directory is updated"
msgstr "Values for auth directory is updated"

#: auth/authentication_directory/models.py:195
#: auth/authentication_directory/models.py:546 auth/models.py:426
#: controller/models.py:251 pool/models.py:481 vm/models.py:105
msgid "{} {} had remove."
msgstr "Выполнено удаление: {} {}."

#: auth/authentication_directory/models.py:202
#: auth/authentication_directory/models.py:553 auth/models.py:433
#: controller/models.py:258 pool/models.py:488 vm/models.py:112
msgid "Soft_delete exception: {}"
msgstr "Ошибка удаления: {}"

#: auth/authentication_directory/models.py:217
msgid "Arguments: {} of group: {}"
msgstr "Аргументы: {} группы: {}"

#: auth/authentication_directory/models.py:218
msgid "Mapping for auth directory {} is created"
msgstr "Отображение для директории авторизации {} создано"

#: auth/authentication_directory/models.py:237
msgid "New arguments: {} of group: {}"
msgstr "Новые аргументы: {} группы: {}"

#: auth/authentication_directory/models.py:238
msgid "Mapping for auth directory {} is updated"
msgstr "Mapping for auth directory {} is updated"

#: auth/authentication_directory/models.py:254
msgid "Authentication directory server {} is down."
msgstr "Сервер директории авторизации {} не работает."

#: auth/authentication_directory/models.py:257
msgid "Authentication directory server {} is connected"
msgstr "Сервер директории авторизации {} подключен"

#: auth/authentication_directory/models.py:339
msgid "Username must be a string."
msgstr "Имя пользователя должно быть строкой."

#: auth/authentication_directory/models.py:364
msgid "Assigning veil groups to {}"
msgstr "Присвоение групп veil {}"

#: auth/authentication_directory/models.py:377
msgid "Mappings: {}"
msgstr "Отображения: {}"

#: auth/authentication_directory/models.py:381
msgid "Role VM_OPERATOR has assigned to user {}."
msgstr "Пользователю {} назначена роль VM_OPERATOR."

#: auth/authentication_directory/models.py:395
msgid "escaped values: {}"
msgstr "cкрытые значения: {}"

#: auth/authentication_directory/models.py:396
msgid "role mapping value type: {}"
msgstr "nип значений отображения роли: {}"

#: auth/authentication_directory/models.py:405
msgid "{}"
msgstr "{}"

#: auth/authentication_directory/models.py:406
msgid "User veil groups: {}"
msgstr "Группы пользователей veil: {}"

#: auth/authentication_directory/models.py:409
msgid "Attaching user {} to group: {}"
msgstr "Прикрепление пользователя {} к группе {}"

#: auth/authentication_directory/models.py:422
#: auth/authentication_directory/models.py:435 tests/test_auth_v2.py:109
msgid "No authentication directory controllers."
msgstr "Переданная запись отсутствует в системе."

#: auth/authentication_directory/models.py:460
msgid "Invalid credentials (ldap): {}"
msgstr "Неверные учетные данные (ldap): {}"

#: auth/authentication_directory/models.py:467
msgid "Server down (ldap)."
msgstr "Сервер не отвечает (ldap)."

#: auth/group_schema.py:26 auth/group_schema.py:105
msgid "No such group."
msgstr "Отсутствует такая группа."

#: auth/group_schema.py:34
msgid "verbose name must me <= 128 characters."
msgstr "verbose name должен быть <= 128 символов"

#: auth/group_schema.py:35
msgid "verbose_name is empty."
msgstr "verbose name пустое."

#: auth/group_schema.py:46
msgid "users list is empty."
msgstr "список пользователей пуст."

#: auth/group_schema.py:51
msgid "Last name length must be <= 255 characters."
msgstr "Фамилия должна быть <= 255 символам."

#: auth/group_schema.py:168
msgid "Group"
msgstr "Группа"

#: auth/handlers.py:23
msgid "Missing request body"
msgstr "Отсутствует тело запроса"

#: auth/handlers.py:25
msgid "Missing username and password"
msgstr "Отсутствует имя пользователя и пароль"

#: auth/handlers.py:30
msgid "Missing username"
msgstr "Отсутствует имя пользователя"

#: auth/handlers.py:32 tests/test_auth_v2.py:51
msgid "Missing password"
msgstr "Отсутствует пароль"

#: auth/handlers.py:42 tests/test_auth_v2.py:35 tests/test_auth_v2.py:43
msgid "Invalid credentials"
msgstr "Неверные полномочия"

#: auth/handlers.py:49
#, python-brace-format
msgid "Authentication failed: {err}"
msgstr "Ошибка авторизации {err}"

#: auth/handlers.py:51
#, python-brace-format
msgid " for user {username}"
msgstr " для пользователя {username}"

#: auth/handlers.py:52
#, python-brace-format
msgid ". IP: {ip}"
msgstr ". IP: {ip}"

#: auth/handlers.py:64
msgid "User {} logout with token {}"
msgstr "Пользователь {} вышел из системы с токеном {}"

#: auth/handlers.py:73
msgid "Demo version"
msgstr "Демонстрационная версия"

#: auth/license/handlers.py:40
msgid "Bad extension."
msgstr "Недопустимое расширение."

#: auth/license/handlers.py:48
msgid "Fail to open license key file."
msgstr "Не удалось открыть лицензионный ключ."

#: auth/license/handlers.py:50
msgid "Try to upload invalid license key"
msgstr "Неудачная попытка загрузить лицензионный ключ"

#: auth/license/handlers.py:53
msgid "Valid license key is uploaded"
msgstr "Лицензионный ключ загружен"

#: auth/models.py:142
msgid "Role {} is added to user {}"
msgstr "Роль {} назначена пользователю {}"

#: auth/models.py:146 auth/models.py:166
msgid "User {} roles: {}"
msgstr "Роли пользователя {}: {}"

#: auth/models.py:149
msgid "Role {} is assigned to user {}"
msgstr "Роль {} назначена пользователю {}"

#: auth/models.py:161
msgid "Roles: {} was deleted to user {}"
msgstr "Роли: {} удалены у пользователя {}"

#: auth/models.py:174
msgid "Group {} is removed for user {}"
msgstr "Группа {} удалена у пользователя {}"

#: auth/models.py:180
#, python-brace-format
msgid "User {username} has been activated."
msgstr "Пользователь {username} активирован."

#: auth/models.py:192
msgid "There is no more active superuser."
msgstr "Больше нет активного суперпользователя."

#: auth/models.py:197
#, python-brace-format
msgid "User {username} has been deactivated."
msgstr "Пользователь {username} деактивирован."

#: auth/models.py:225
#, python-brace-format
msgid "Password of user {username} has been changed."
msgstr "Пароль пользователя {username} изменен."

#: auth/models.py:243
msgid "User {} created with role {}."
msgstr "Пользователь {} создан с ролью {}."

#: auth/models.py:266 auth/models.py:270
msgid "Roles: {}"
msgstr "Роли: {}"

#: auth/models.py:267
#, python-brace-format
msgid "User {username} has become a superuser."
msgstr "Пользователь {username} стал суперпользователем."

#: auth/models.py:271
#, python-brace-format
msgid "User {username} has left a superuser."
msgstr "Пользователь {username} перестал быть суперпользователем."

#: auth/models.py:275
msgid "Values of user {} is changed"
msgstr "Параметры пользователя {} изменены"

#: auth/models.py:291
#, python-brace-format
msgid "{auth_type}: user {username} has been logged in successfully. IP: {ip}."
msgstr "{auth_type}: пользователь {username} успешно зарегистрирован. IP: {ip}."

#: auth/models.py:312
#, python-brace-format
msgid "User {username} has logged out."
msgstr "Пользователь {username} вышел из системы."

#: auth/models.py:403
msgid "Group {} is created."
msgstr "Группа {} создана."

#: auth/models.py:418
msgid "Values of group {} is updated"
msgstr "Параметры группы {} обновлены"

#: auth/models.py:442
msgid "User {} has been included to group {}."
msgstr "Пользователь {} был включен в группу {}."

#: auth/models.py:446
msgid "User {} is already in group {}"
msgstr "Пользователь {} уже находится в группе {}"

#: auth/models.py:456
msgid "Removing user {} from group {}"
msgstr "Удаление пользователя {} из группы {}"

#: auth/models.py:463
msgid "Role {} has been set to group {}."
msgstr "Роль {} добавлена в группу {}."

#: auth/models.py:467
msgid "Group {} has already role {}"
msgstr "Группе {} уже назначена роль {}."

#: auth/models.py:477
msgid "Roles: {} was deleted to group {}"
msgstr "Роли: {} удалены из группы {}"

#: auth/user_schema.py:24 auth/user_schema.py:158
msgid "No such user."
msgstr "Нет такого пользователя."

#: auth/user_schema.py:34
msgid "username must contain >= 3 chars (letters, digits, _, -, +) and can't contain any spaces"
msgstr "username должно быть >= 3 символов (буквы, цифры, _, -, +) и не содержать пробелов"

#: auth/user_schema.py:41
msgid "Email {} is already busy"
msgstr "Email {} уже используется"

#: auth/user_schema.py:49
msgid "Email must contain English characters and/or digits, @ and domain name."
msgstr "Email должен содержать символы латинского алфавита и/или цифры, иметь @ и домен."

#: auth/user_schema.py:64
msgid "First name length must be <= 32 characters."
msgstr "Имя должно быть <= 32 символов."

#: auth/user_schema.py:70
msgid "Last name length must be <= 128 characters."
msgstr "Фамилия должна быть <= 128 символам."

#: auth/user_schema.py:154
msgid "Scpecify id or username."
msgstr "Укажите ID или имя пользователя."

#: auth/utils/veil_jwt.py:26
msgid "Token invalid."
msgstr "Недействительный токен."

#: auth/utils/veil_jwt.py:28
msgid "jwtauth: jwt.ExpiredSignature"
msgstr "jwtauth: jwt.ExpiredSignature"

#: auth/utils/veil_jwt.py:31
msgid "Token expired."
msgstr "Срок действия токена истек."

#: auth/utils/veil_jwt.py:34
msgid "jwtauth: Assertion error {}"
msgstr "jwtauth: ошибка утверждения {}."

#: auth/utils/veil_jwt.py:84
msgid "Error with JWT decode"
msgstr "Ошибка JWT декодирования."

#: auth/utils/veil_jwt.py:94 auth/utils/veil_jwt.py:96
#: auth/utils/veil_jwt.py:98
msgid "invalid header authorization"
msgstr "недействительный заголовок авторизации"

#: auth/utils/veil_jwt.py:102
msgid "Missing Authorization header"
msgstr "Пропущен заголовок авторизации"

#: common/veil_client.py:50
msgid "jwt {}"
msgstr "jwt {}"

#: common/veil_client.py:89
msgid "Controller {} connection error"
msgstr "Ошибка подключения к контроллеру {}"

#: common/veil_client.py:99
msgid "url: {} - {}"
msgstr "url: {} - {}"

#: common/veil_client.py:109
msgid "Controller {} connection error."
msgstr "Ошибка подключения к контроллеру {}."

#: common/veil_client.py:113
msgid "URL not found"
msgstr "URL не найден"

#: common/veil_client.py:131
msgid "Can't process Content-Type."
msgstr "Не может обработаться Content-Type."

#: common/veil_client.py:134
msgid "Only 'json' Content-Type."
msgstr "Content-Type только 'json'."

#: common/veil_decorators.py:27
msgid "'body' index in args must be 4, but in the same time 'body' in kwargs"
msgstr "Индекс 'body' это 4 параметра в аргументах. Но в то же время 'body' в kwargs."

#: common/veil_decorators.py:68
msgid "Can check only kwargs or args. Not both at the same time."
msgstr "Можете проверить только kwargs или аргументы. Не оба обдовременно."

#: common/veil_decorators.py:73 common/veil_decorators.py:87
msgid "The parameters to be checked are in an dict. Can't explicitly match values with tuple."
msgstr "Параметры, которые нужно проверить, указаны в формате словаря. Значения не могут явно сопоставиться с кортежем."

#: common/veil_decorators.py:83
msgid "Value {} is invalid. Valid values are: {}"
msgstr "Значение {} неверно. Допустимые значения: {}"

#: common/veil_decorators.py:90
msgid "Parameter {} is necessary."
msgstr "Параметр {} необходим."

#: common/veil_decorators.py:95
msgid "Parameter {} value {} is invalid. Valid values are: {}"
msgstr "Параметр {} значения {} неверный. Допустимые значения: {}"

#: common/veil_decorators.py:128
msgid "IP: {}. username: {}"
msgstr "IP: {}. Пользователь: {}."

#: common/veil_decorators.py:130 tests/test_auth_v2.py:75
msgid "Invalid permissions"
msgstr "Недостаточно прав"

#: common/veil_errors.py:167
msgid "Controller is not available."
msgstr "Контроллер недоступен."

#: common/veil_errors.py:185
msgid "Unable to logon to system using these credentials."
msgstr "Не удалось войти в систему с предоставленными учетными данными."

#: common/veil_errors.py:191
msgid "401: Unauthorized."
msgstr "Ошибка 401: проблема с авторизацией."

#: common/veil_errors.py:197
msgid "Critical controller error."
msgstr "Критическая ошибка контроллера."

#: common/veil_validators.py:32
msgid "Field \"{}\" - {}"
msgstr "Поле \"{}\" - {}"

#: controller/client.py:28
msgid "Auth failed."
msgstr "Ошибка авторизации."

#: controller/models.py:102 controller/models.py:136
msgid "No such controller"
msgstr "Нет такого контроллера."

#: controller/models.py:142 controller/models.py:157
msgid "Checking controller credentials: address: {}, username: {}, ldap_connection: {}"
msgstr "Проверка учетных данных контроллера: адрес: {}, имя: {}, ldap_connection: {}"

#: controller/models.py:148
msgid "Controller {} check failed."
msgstr "Проверка контроллера {} не удалась."

#: controller/models.py:149
msgid "Controller check: {}"
msgstr "Проверка контроллера: {}"

#: controller/models.py:151
msgid "Controller {} check passed successful."
msgstr "Проверка контроллера {} прошла успешно."

#: controller/models.py:163
msgid "Get controller credentials: Controller's {} credentials are good."
msgstr "Получение учетных данных контроллера: Хорошие учетные данные контроллера {}."

#: controller/models.py:187
msgid "Successfully added new controller {} with address {}."
msgstr "Успешно добавлен новый контроллер {} с адресом {}."

#: controller/models.py:223
msgid "Can't connect to controller {} with username: {}, ldap_connection: {}"
msgstr "Не подключается к контроллеру {} с именем: {}, ldap_connection: {}"

#: controller/models.py:231
msgid "Can't login login to controller {}"
msgstr "Не получается войти на контроллер {}"

#: controller/models.py:235
msgid "Successfully update controller {} with address {}."
msgstr "Успешно обновлен контроллер {} с адресом {}."

#: controller/models.py:247
msgid "Controller has pool of virtual machines. Please completely remove."
msgstr "У контроллера есть пулы виртуальных машин. Выполните полное удаление."

#: controller/models.py:271
#, python-brace-format
msgid "Controller {name} had completely remove."
msgstr "Выполнено полное удаление контроллера {name}."

#: controller/models.py:285
msgid "Controller {} has been activated."
msgstr "Контроллер {} активирован."

#: controller/models.py:303
msgid "Controller {} has been deactivated."
msgstr "Контроллер {} деактивирован."

#: controller/schema.py:67
msgid "Controller name cannot be empty."
msgstr "Имя контроллера не может быть пустым."

#: controller/schema.py:75
#, python-brace-format
msgid "Add new controller with address {address}: operation failed."
msgstr "Ошибка добавления нового контроллера с адресом {address}."

#: controller/schema.py:100 controller/schema.py:143 controller/schema.py:166
#: controller/schema.py:195
msgid "No such controller."
msgstr "Нет такого контроллера."

#: controller/schema.py:117
#, python-brace-format
msgid "Fail to update controller {id}: {error}"
msgstr "Ошибка обновления контроллера {id}: {error}"

#: controller/schema.py:148
msgid "Controller"
msgstr "Контроллер"

#: controller_resources/schema.py:321 controller_resources/schema.py:374
#: controller_resources/schema.py:426
msgid "The sort parameter is incorrect"
msgstr "Неверный параметр сортировки"

#: database.py:83
msgid "Incorrect sort parameter {}"
msgstr "Неверный параметр сортировки {}"

#: database.py:93
msgid "Incorrect request parameter {}"
msgstr "Неверный параметр запроса {}"

#: journal/event/schema.py:148
msgid "No such event."
msgstr "Нет такого события."

#: journal/event/schema.py:193
msgid "Journal is clear."
msgstr "Журнал очищен."

#: pool/models.py:157
msgid "Incorrect sorting option {}."
msgstr "Неверный параметр сортировки {}."

#: pool/models.py:373
msgid "User {} has been included to pool {}"
msgstr "Пользователь {} был включен в пул {}"

#: pool/models.py:375 pool/models.py:402
msgid "Pool already has permission."
msgstr "Пул уже имеет разрешение."

#: pool/models.py:386
msgid "Removing user {} from pool {}"
msgstr "Удаление пользователя {} из пула {}"

#: pool/models.py:400
msgid "Group {} has been included to pool {}"
msgstr "Группа {} была включена в пул {}"

#: pool/models.py:413
msgid "Removing group {} from pool {}"
msgstr "Удаление группы {} из пула {}"

#: pool/models.py:426
msgid "Role {} has been set to pool {}."
msgstr "Роль {} добавлена в пул {}."

#: pool/models.py:428
msgid "Pool already has role."
msgstr "Пул уже имеет роль."

#: pool/models.py:438
msgid "Roles: {} was deleted to pool {}"
msgstr "Роли: {} удалены в пуле {}"

#: pool/models.py:463
msgid "Controller {} not found."
msgstr "Контроллер {} не найден."

#: pool/models.py:477
msgid "Pool has VMs. Please completely remove."
msgstr "У пула виртуальных машин есть виртуальные машины. Выполните полное удаление."

#: pool/models.py:501
#, python-brace-format
msgid "Complete removal pool of desktops {verbose_name} is done."
msgstr "Выполнено полное удаление пула рабочих столов {verbose_name}."

#: pool/models.py:509
msgid "Pool {} has been activated."
msgstr "Пул {} активирован."

#: pool/models.py:516
msgid "Pool {} has been deactivated."
msgstr "Пул {} деактивирован."

#: pool/models.py:589
msgid "HttpError: {}"
msgstr "Ошибка Http: {}"

#: pool/models.py:598
msgid "VM with id {} not found in any controllers"
msgstr "Виртуальная машина с {} ID не найдена ни на одном из известных контроллеров"

#: pool/models.py:604
msgid "StaticPool: Check that all vms are on the same node"
msgstr "Статический пул: Убедитесь, что все виртуальные машины находятся на одном узле"

#: pool/models.py:617
msgid "StaticPool: Create Pool"
msgstr "Статический пул: создание пула"

#: pool/models.py:625
msgid "StaticPool: Create StaticPool"
msgstr "Статический пул: создание статического пула"

#: pool/models.py:628
msgid "StaticPool: Create VMs"
msgstr "Статический пул: создание виртуальных машин"

#: pool/models.py:630
msgid "VM info {}"
msgstr "Информация о ВМ {}"

#: pool/models.py:636
msgid "VM {} created."
msgstr "ВМ {} создана."

#: pool/models.py:638
msgid "Static pool {} created."
msgstr "Статический пул {} создан."

#: pool/models.py:652
msgid "Static pool {} is updated."
msgstr "Статический пул {} обновлен."

#: pool/models.py:747
msgid "Create Pool {}"
msgstr "Создание пула {}"

#: pool/models.py:755
msgid "Create AutomatedPool {}"
msgstr "Создание автоматического пула {}"

#: pool/models.py:790
msgid "Update Pool values for AutomatedPool {}"
msgstr "Обновление значений пула для автоматического пула {}"

#: pool/models.py:805
msgid "Update AutomatedPool values for {}"
msgstr "Обновление значений автоматического пула для {}"

#: pool/models.py:809
#, python-brace-format
msgid "Automated pool {name} updated."
msgstr "Автоматический пул {name} обновлен."

#: pool/models.py:835
msgid "add_domain {}, attempt № {}, of {}"
msgstr "Добавление домена {}, попытка № {} из {}"

#: pool/models.py:839
msgid "VM creation task id: {}"
msgstr "ID задачи создания виртуальной машины: {}"

#: pool/models.py:843
msgid "Fail to create VM on ECP. Re-run."
msgstr "Ошибка создания виртуальной машины на ECP. Перезапустите."

#: pool/models.py:849
msgid "Subscribe to ws messages."
msgstr "Подпишитесь на сообщения ws."

#: pool/models.py:854
msgid "Wait for result."
msgstr "Ожидайте результата."

#: pool/models.py:860
msgid "Create virtual machine"
msgstr "Создание виртуальной машины."

#: pool/models.py:893
msgid "Could not get the response about result of creation VM on ECP by WS. Task status check."
msgstr "Не удалось получить ответ о результате создания ВМ на ECP по WS. Проверим статус задачи."

#: pool/models.py:897
msgid "Probably task is not done. Check VM status."
msgstr "Вероятно, задание не выполнено. Проверьте состояние ВМ."

#: pool/models.py:920
msgid "VM {} is added to Automated pool {}"
msgstr "Виртуальная машина добавлена в автоматический пул {}"

#: pool/models.py:925
msgid "Error with create VM {} was {} times."
msgstr "Ошибка с созданием виртуальной машины {} была {} раз."

#: pool/models.py:937
msgid "Add {} initial vms for pool {}. Controller address: {}"
msgstr "Добавление {} начальных виртуальных машин для пула {}. Адрес контроллера: {}."

#: pool/models.py:944
msgid "Pool {} os type is: {}"
msgstr "Операционная система пула {}: {}"

#: pool/models.py:947
msgid "Automated pool creation started"
msgstr "Автоматическое создание пула началось"

#: pool/models.py:958
msgid "Created {} VMs from {} at the Automated pool {}"
msgstr "Создание {} виртуальных машин из {} автоматического пула {}"

#: pool/models.py:975
msgid "Can't create VM"
msgstr "Невозможно создать виртуальную машину"

#: pool/models.py:981
msgid "Initial VM amount {} at the Automated pool {}"
msgstr "Начальное количество виртуальных машин {} в автоматическом пуле {}"

#: pool/models.py:984
msgid "Automated pool created with errors. VMs created: {}. Required: {}"
msgstr "Автоматический пул создан с ошибками. Созданные виртуальные машины: {}. Необходимо: {}."

#: pool/models.py:1001
msgid "Could not create the required number of machines."
msgstr "Не удалось создать необходимое количество машин."

#: pool/models.py:1050
msgid "VM creating error:"
msgstr "Ошибка создания виртуальной машины:"

#: pool/models.py:1056
msgid "Delete VMs for AutomatedPool {}"
msgstr "Удаление виртуальных машин для автоматического пула {}"

#: pool/models.py:1059
msgid "Calling soft delete for vm {}"
msgstr "Вызов мягкого удаления для виртуальной машины {}"

#: pool/models.py:1060 vm/models.py:234
msgid "VM"
msgstr "Виртуальная машина"

#: pool/pool_task_manager.py:70
msgid "Logic error: no such pool"
msgstr "Логическая ошибка: нет такого пула"

#: pool/schema.py:55 pool/schema.py:362 pool/schema.py:389
msgid "No such pool."
msgstr "Нет такого пула."

#: pool/schema.py:67
msgid "ip-address probably invalid."
msgstr "Возможно, неверный IP адрес."

#: pool/schema.py:77
msgid "Pool name must contain only characters, digits, _, -"
msgstr "Имя пула должно содержать только буквы, цифры, _, -"

#: pool/schema.py:88
msgid "Template name of VM must contain only characters, digits, _, -"
msgstr "Шаблонное имя вм должно содержать только буквы, цифры, _, -"

#: pool/schema.py:96
msgid "Initial number of VM must be in {}-{} interval"
msgstr "Начальное число виртуальных машин должно быть в интервале {}-{}."

#: pool/schema.py:112
msgid "Number of created VM must be in {}-{} interval"
msgstr "Число создаваемых виртуальных машин должно быть в интервале {}-{}."

#: pool/schema.py:133 pool/schema.py:683
msgid "Maximal number of created VM should be less than initial number of VM"
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше начального числа ВМ"

#: pool/schema.py:135 pool/schema.py:685
msgid "Maximal number of created VM must be in [{} {}] interval"
msgstr "Максимальное число создаваемых виртуальных машин должно быть в интервале [{} {}]."

#: pool/schema.py:380
msgid "Pool"
msgstr "Пул"

#: pool/schema.py:449
msgid "StaticPool: Get additional info from Veil"
msgstr "Статический пул: получение дополнительной информации о Veil"

#: pool/schema.py:457
msgid "All of VM must be at one server"
msgstr "Все виртуальные машины должны быть на одном сервере"

#: pool/schema.py:459
msgid "StaticPool: Determine cluster"
msgstr "Статический пул: Определение кластера"

#: pool/schema.py:467
msgid "VM has no disks."
msgstr "ВМ не имеет дисков."

#: pool/schema.py:480
msgid "Failed to create static pool {}."
msgstr "Ошибка создания статического пула {}."

#: pool/schema.py:500 pool/schema.py:554
msgid "List of VM should not be empty"
msgstr "Список виртуальных машин не должен быть пустым."

#: pool/schema.py:513
msgid "VM ids: {}"
msgstr "ID виртуальных машин: {}"

#: pool/schema.py:518
msgid "VM {} is at server different from pool server now"
msgstr "ВМ {} находится на сервере отличном от сервера пула."

#: pool/schema.py:521
msgid "VM {} is already in one of pools"
msgstr "Виртуальная машина {} уже в одном из пулов."

#: pool/schema.py:526
msgid "All VMs on node: {}"
msgstr "Все виртуальные машины на узле: {}"

#: pool/schema.py:537
msgid "Vm {} is added to pool {}"
msgstr "Виртуальная машина {} добавлена в пул {}"

#: pool/schema.py:563
msgid "VM doesn't belong to specified pool"
msgstr "Виртуальная машина не принадлежит заданному пулу"

#: pool/schema.py:591
msgid "Failed to update static pool {}. Name must be unique."
msgstr "Ошибка редактирования статического пула {}. Имя должно быть уникальным."

#: pool/schema.py:632
msgid "Failed to create automated pool {}. Name must be unique."
msgstr "Ошибка создания автоматического пула {}. Имя должно быть уникальным."

#: pool/schema.py:688
msgid "Maximal number of created VM can not be reduced."
msgstr "Максимальное количество создаваемых виртуальных машин не может быть уменьшено."

#: pool/schema.py:706
msgid "Failed to update automated pool {}. Name must be unique."
msgstr "Ошибка редактирования автоматического пула {}. Имя должно быть уникальным."

#: resources_monitoring/handlers.py:79
msgid "destructor VdiFrontWsHandler"
msgstr "Деструктор VdiFrontWsHandler"

#: resources_monitoring/handlers.py:92
msgid "Message: {}"
msgstr "Сообщение: {}"

#: resources_monitoring/handlers.py:106
msgid "Unknown subscription source"
msgstr "Неизвестный источник подписки"

#: resources_monitoring/handlers.py:117
msgid "already subscribed"
msgstr "уже подписан"

#: resources_monitoring/handlers.py:121
msgid "not subscribed"
msgstr "не подписан"

#: resources_monitoring/handlers.py:132
msgid "WebSocket closed"
msgstr "WebSocket закрыт"

#: resources_monitoring/handlers.py:164
msgid "Write error"
msgstr "Ошибка записи"

#: resources_monitoring/resources_monitor.py:104
msgid "{} is connected: {}"
msgstr "{} подключен: {}"

#: resources_monitoring/resources_monitor.py:137
#, python-brace-format
msgid "{cls}: an not connect to {ip}"
msgstr "{cls}: не подключен к {ip}."

#: resources_monitoring/resources_monitor.py:146
msgid "add {}"
msgstr "добавление {}"

#: resources_monitoring/resources_monitor.py:167
msgid "{} Closing ws connection {}"
msgstr "{} Закрытие ws соединения {}"

#: resources_monitoring/resources_monitor_manager.py:27
#, python-brace-format
msgid "{cls}: connected controllers -- {controllers}"
msgstr "{cls}: подключенные контроллеры -- {controllers}."

#: resources_monitoring/resources_monitor_manager.py:36
msgid "{}: Started"
msgstr "{}: Запущен"

#: resources_monitoring/resources_monitor_manager.py:71
#, python-brace-format
msgid "{cls}: Controller {ip} is already monitored!"
msgstr "{cls}: Контроллер {ip} уже отслеживается!"

#: resources_monitoring/resources_monitor_manager.py:78
#, python-brace-format
msgid "{cls}: resource monitor for controller {ip} connected"
msgstr "{cls}: монитор ресурсов для контроллера {ip} подключен"

#: resources_monitoring/resources_monitor_manager.py:93
#, python-brace-format
msgid "{cls}: controller {ip} is not monitored!"
msgstr "{cls}: контроллер {ip} не отслеживается!"

#: resources_monitoring/resources_monitor_manager.py:101
#, python-brace-format
msgid "{cls}: resource monitor for controller {ip} removed"
msgstr "{cls}: удален монитор ресурсов для контроллера {ip}"

#: tests/test_auth_v2.py:125
msgid "Invalid credentials (ldap)"
msgstr "Неверные учетные данные (ldap)"

#: thin_client_api/handlers.py:65
msgid "Thin client limit exceeded."
msgstr "Превышен лимит тонких клиентов."

#: thin_client_api/handlers.py:74
msgid "Pool not found."
msgstr "Пул не найден."

#: thin_client_api/handlers.py:85
msgid "User does not have permission to use pool."
msgstr "Пользователь не имеет разрешения на использование пула."

#: thin_client_api/handlers.py:118
msgid "Pool has not free machines"
msgstr "В пуле нет свободных машин"

#: thin_client_api/handlers.py:145
msgid "VM does not support RDP"
msgstr "Виртуальная машина не поддерживает RDP"

#: thin_client_api/handlers.py:168
msgid "User {} not found."
msgstr "Пользователь {} не найден."

#: thin_client_api/handlers.py:171
msgid "There is no pool with id: {}"
msgstr "Отсутствует пул с ID: {}."

#: thin_client_api/handlers.py:175
msgid "User {} has no VM on pool {}"
msgstr "У пользователя {} нет виртуальной машины в пуле {}"

#: vm/models.py:77
msgid "Create VM {} on VDI DB."
msgstr "Создание виртуальной машины {} на VDI DB."

#: vm/models.py:88
msgid "VM {} is created"
msgstr "Виртуальная машина {} создана"

#: vm/models.py:100
msgid "Fail to remove VM {} from ECP: "
msgstr "Ошибка удаления ВМ {} из ECP: "

#: vm/models.py:101
msgid "Vm {} removed from ECP."
msgstr "ВМ {} удалена из ECP."

#: vm/models.py:124
msgid "User {} is added to VM {}"
msgstr "Пользователь {} назначен виртуальной машине {}"

#: vm/models.py:126
msgid "Vm already has permission."
msgstr "Вм уже имеет разрешение"

#: vm/models.py:137
msgid "VM {} is clear from users"
msgstr "ВМ {} освобождена от пользователей"

#: vm/models.py:185
msgid "Trying to create VM on ECP with verbose_name={}"
msgstr "Попытка создать виртуальную машину на ECP с verbose_name = {}"

#: vm/models.py:191
msgid "Request to create VM sent without surprise. Leaving while."
msgstr "Запрос на создание ВМ отправлен без неожиданностей. Покидаем while."

#: vm/models.py:199
msgid "ECP error: {}"
msgstr "Ошибка ECP: {}"

#: vm/models.py:202
msgid "Bad domain name {}"
msgstr "Неверное доменное имя {}"

#: vm/models.py:207
msgid "Controller has not free space for creating new VM."
msgstr "На контроллере отсутствует место для создания новой виртуальной машины."

#: vm/models.py:208
msgid "Not enough free space on data pool"
msgstr "Недостаточно свободного места в пуле данных"

#: vm/models.py:212
msgid "Possibly blocked by active task on ECP. Wait before next try."
msgstr "Возможно, заблокировано активным заданием на ECP. Подождите перед следующей попыткой."

#: vm/models.py:215
msgid "Something went wrong. Interrupt while."
msgstr "Что-то пошло не так. Прерываем while."

#: vm/models.py:219
msgid "Wait one more try"
msgstr "Подождите еще одну попытку."

#: vm/models.py:235
msgid "Vm {} removed from pool"
msgstr "ВМ {} удалена из пула"

#: vm/schema.py:156
msgid "There is no VM {}"
msgstr "Нет ВМ {}."

#: vm/schema.py:172
msgid "User does not have the right to use pool, which has VM."
msgstr "У пользователя нет прав на использование пула, которому принадлежит ВМ."

#: vm/schema.py:216
msgid "GraphQL: Resolving template info"
msgstr "GraphQL: разрешение информации о шаблоне."

#: vm/schema.py:221
msgid "Template data could not be retrieved: {}"
msgstr "Не удалось получить данные Шаблона: {}"

#: vm/schema.py:231
msgid "VM data could not be retrieved: {}"
msgstr "Не удалось получить данные виртуальной машины: {}"

#: vm/schema.py:242
msgid "Templates list could not be retrieved: {}"
msgstr "Не удалось получить список шаблонов: {}"

#: vm/schema.py:278 vm/schema.py:356
msgid "Incorrect sort parameter"
msgstr "Неверный параметр сортировки"

#: vm/schema.py:286
msgid "GraphQL: Resolving VMs"
msgstr "GraphQL: разрешение виртуальных машин"

#: vm/schema.py:293
msgid "VMs list could not be retrieved: {}"
msgstr "Не удалось получить список виртуальных машин: {}"

#: vm/schema.py:298
msgid "GraphQL: VM type list:"
msgstr "GraphQL: список типов виртуальных машин:"

#~ msgid "OU: {}"
#~ msgstr "Подразделения: {}"

#~ msgid "AD user info: {}"
#~ msgstr "Информация пользователя AD: {}"

#~ msgid "GROUPS: {}"
#~ msgstr "Группы: {}"

#~ msgid "AD user groups: {}"
#~ msgstr "Группы пользователей AD: {}"

#~ msgid "User name must contain minimum 3 characters. It must contain letters and digits, _, -, +."
#~ msgstr "Имя пользователя должно содержать буквы, цифры, _, -, + и быть не короче 3 символов."

#~ msgid "AutomatedPool {} is created"
#~ msgstr "Автоматический пул {} создан"

#~ msgid "Subclasses of BasePasswordHasher must provide a verify() method"
#~ msgstr "Подклассы BasePasswordHasher должны предоставлять метод verify()"

#~ msgid "Group {} roles: {}"
#~ msgstr "Роли группы {}: {}"

#~ msgid "Create Pool"
#~ msgstr "Создание пула"

#~ msgid "Hasher %r doesn't specify a library attribute"
#~ msgstr "Hasher %r не указывает атрибут библиотеки"

#~ msgid "Mapping {} for auth directory {} is deleted"
#~ msgstr "Мэппинг {} для AD {} удален"

#~ msgid "License information:"
#~ msgstr "Информация о лицензии:"

#~ msgid "Group {} is deleted"
#~ msgstr "Группа {} удалена"

#~ msgid "Automated pool creation. Created {} VMs from {}"
#~ msgstr "Автоматическое создание пула. Создание {} виртуальных машин из {}"

#~ msgid "Error with controller update: {}"
#~ msgstr "Ошибка с обновлением контроллера {}."

#~ msgid "Removal pool of desktops {verbose_name} is done."
#~ msgstr "Выполнено удаление пула рабочих столов {verbose_name}."

#~ msgid "IP: . username: {}"
#~ msgstr "IP: . пользователь: {}"

#~ msgid "Can't create VM:"
#~ msgstr "Невозможно создать виртуальную машину:"

#~ msgid "Couldn't load {} algorithm library: {}"
#~ msgstr "Не может загрузиться %r библиотека алгоритмов: %s"

#~ msgid "Authentication directory {} is deleted"
#~ msgstr "Сервер директории авторизации {} не работает."

#~ msgid "{role} \"{username}\" created."
#~ msgstr "{role} пользователя {username} создана."

#~ msgid "StaticPool: Objects on VDI DB created."
#~ msgstr "Статический пул: объекты на VDI DB созданы."

#~ msgid "Subclasses of BasePasswordHasher should provide a harden_runtime() method"
#~ msgstr "Подклассы BasePasswordHasher должны предоставлять метод harden_runtime()"

#~ msgid "URL {url} - {http_error}"
#~ msgstr "URL {url} - {http_error}"

#~ msgid "Automated pool successfully created. Initial VM amount {}"
#~ msgstr "Автоматический пул успешно создан. Начальное количество виртуальных машин {}"

#~ msgid "Subclasses of BasePasswordHasher must provide an encode() method"
#~ msgstr "Подклассы BasePasswordHasher должны предоставлять метод encode()"
