# Russian translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Emil <e.gareev@mashtab.org>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-03-17 18:14+0300\n"
"PO-Revision-Date: 2020-03-16 17:13+0300\n"
"Last-Translator: Emil <e.gareev@mashtab.org>\n"
"Language-Team: Russian\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: app.py:121
msgid "Tornado VDI started"
msgstr "Tornado VDI запущен."

#: app.py:125
msgid "Auth is disabled. Enable on production!"
msgstr "Авторизация недоступна. Включите при создании!"

#: app.py:140
msgid "Stopping Tornado VDI"
msgstr "Остановка Tornado VDI."

#: app.py:142
msgid "Stopping resources_monitor_manager"
msgstr "Остановка менеджера мониторинга ресурсов."

#: app.py:145
msgid "Stopping GINO"
msgstr "Остановка GINO."

#: app.py:148
msgid "Stopping IOLoop"
msgstr "Остановка IOLoop."

#: app.py:151
msgid "Tornado VDI stopped"
msgstr "Tornado VDI остановлен."

#: auth/authentication_directory/auth_dir_schema.py:31
#: auth/authentication_directory/auth_dir_schema.py:163
msgid "No such Authentication Directory."
msgstr "Отсутствует такая директория авторизации."

#: auth/authentication_directory/auth_dir_schema.py:37
msgid "Authentication directory URL should start with ldap(s)://."
msgstr "Ссылка на директорию авторизации должна начинаться с ldap(s)://."

#: auth/authentication_directory/auth_dir_schema.py:44
msgid "Verbose name should not be empty."
msgstr "Имя verbose не должно быть пустым."

#: auth/authentication_directory/auth_dir_schema.py:60 auth/group_schema.py:41
msgid "users count not much with db count."
msgstr "Счетчик пользователей не коррелирует с счетчиком БД."

#: auth/authentication_directory/auth_dir_schema.py:62
msgid "groups list is empty."
msgstr "Список групп пуст."

#: auth/authentication_directory/auth_dir_schema.py:69
msgid "No such mapping."
msgstr "Нет такого отображения."

#: auth/authentication_directory/auth_dir_schema.py:159
msgid "Specify id."
msgstr "Укажите ID."

#: auth/authentication_directory/models.py:125 tests/test_auth_dir_v2.py:65
msgid "More than one authentication directory can not be created."
msgstr "Не может быть создано более одной директории авторизации."

#: auth/authentication_directory/models.py:239
msgid "Authentication directory server {} is down."
msgstr "Сервер директории авторизации {} не работает."

#: auth/authentication_directory/models.py:278
msgid "AD user info: {}"
msgstr "Информация пользователя AD: {}"

#: auth/authentication_directory/models.py:279
msgid "AD user groups: {}"
msgstr "Группы пользователей AD: {}"

#: auth/authentication_directory/models.py:326
msgid "Username must be a string."
msgstr "Имя пользователя должно быть строкой."

#: auth/authentication_directory/models.py:351
msgid "Assigning veil groups to {}"
msgstr "Присвоение групп veil {}."

#: auth/authentication_directory/models.py:364
msgid "Mappings: {}"
msgstr "Отображения: {}"

#: auth/authentication_directory/models.py:368
msgid "Role VM_OPERATOR has assigned to user {}."
msgstr "Пользователю {} назначена роль VM_OPERATOR."

#: auth/authentication_directory/models.py:375
msgid "OU: {}"
msgstr "Подразделения: {}"

#: auth/authentication_directory/models.py:376
msgid "GROUPS: {}"
msgstr "Группы: {}"

#: auth/authentication_directory/models.py:385
msgid "escaped values: {}"
msgstr "Скрытые значения: {}"

#: auth/authentication_directory/models.py:386
msgid "role mapping value type: {}"
msgstr "Тип значений отображения роли: {}"

#: auth/authentication_directory/models.py:395
msgid "{}"
msgstr "{}"

#: auth/authentication_directory/models.py:396
msgid "User veil groups: {}"
msgstr "Группы пользователей veil: {}"

#: auth/authentication_directory/models.py:399
msgid "Attaching user {} to group: {}"
msgstr "Прикрепление пользователя {} к группе {}."

#: auth/authentication_directory/models.py:413 tests/test_auth_v2.py:109
msgid "No authentication directory controllers."
msgstr "Отсутствует директория авторизации контроллеров."

#: auth/authentication_directory/models.py:438 tests/test_auth_v2.py:125
msgid "Invalid credeintials (ldap)."
msgstr "Неверные полномочия (ldap)."

#: auth/authentication_directory/models.py:445
msgid "Server down (ldap)."
msgstr "Сервер не работает (ldap)."

#: auth/group_schema.py:26 auth/group_schema.py:96
msgid "No such group."
msgstr "Отсутствует такая группа."

#: auth/group_schema.py:32
msgid "verbose_name is empty."
msgstr "Имя verbose пустое."

#: auth/group_schema.py:43
msgid "users list is empty."
msgstr "Список пользователей пуст."

#: auth/handlers.py:22
msgid "Missing request body"
msgstr "Отсутствует тело запроса."

#: auth/handlers.py:24
msgid "Missing username and password"
msgstr "Отсутствует имя пользователя и пароль."

#: auth/handlers.py:29
msgid "Missing username"
msgstr "Отсутствует имя пользователя."

#: auth/handlers.py:31 tests/test_auth_v2.py:51 tests/test_locale_auth.py:26
msgid "Missing password"
msgstr "Отсутствует пароль"

#: auth/handlers.py:38 tests/test_auth_v2.py:35 tests/test_auth_v2.py:43
msgid "Invalid credentials"
msgstr "Неверные полномочия"

#: auth/handlers.py:45
#, python-brace-format
msgid "Authentication failed: {err}"
msgstr "Ошибка авторизации {err}"

#: auth/handlers.py:47
#, python-brace-format
msgid " for user {username}"
msgstr " для пользователя {username}"

#: auth/handlers.py:48
#, python-brace-format
msgid ". IP: {ip}"
msgstr ". IP: {ip}"

#: auth/handlers.py:68
msgid "Demo version"
msgstr "Демонстрационная версия"

#: auth/models.py:102
msgid "User {} roles: {}"
msgstr "Роли пользователя {}: {}"

#: auth/models.py:107
msgid "Group {} roles: {}"
msgstr "Роли группы {}: {}"

#: auth/models.py:147
msgid "Role {} is assigned to user {}"
msgstr "Роль {} назначена пользователю {}."

#: auth/models.py:171
#, python-brace-format
msgid "User {username} has been activated."
msgstr "Пользователь {username} активирован."

#: auth/models.py:183
msgid "There is no more active superuser."
msgstr "Больше нет активного суперпользователя."

#: auth/models.py:188
#, python-brace-format
msgid "User {username} has been deactivated."
msgstr "Пользователь {username} деактивирован."

#: auth/models.py:211
#, python-brace-format
msgid "Password of user {username} has been changed."
msgstr "Пароль пользователя {username} изменен."

#: auth/models.py:229
#, python-brace-format
msgid "{role} \"{username}\" created."
msgstr "{role} {username} создана."

#: auth/models.py:253
#, python-brace-format
msgid "User {username} has become a superuser."
msgstr "Пользователь {username} стал суперпользователем."

#: auth/models.py:270
#, python-brace-format
msgid "{auth_type} user {username} has been logged in successfully. IP: {ip}."
msgstr "{auth_type} пользователь {username} успешно зарегистрирован. IP: {ip}."

#: auth/models.py:291
#, python-brace-format
msgid "User {username} has logged out."
msgstr "Пользователь {username} вышел из системы."

#: auth/models.py:380
#, python-brace-format
msgid "User {username} has been included to group {groupname}."
msgstr "Пользователь {username} был включен в группу {groupname}."

#: auth/models.py:385
msgid "User {} is already in group {}"
msgstr "Пользователь {} уже находится в группе {}."

#: auth/models.py:393
msgid "Removing users: {} from group {}"
msgstr ""

#: auth/models.py:400
#, python-brace-format
msgid "Role {role} has been set to group {groupname}."
msgstr "Удаление пользователей: {} из группы {}."

#: auth/models.py:405
msgid "Group {} has already role {}"
msgstr "Группе {} уже назначена роль {}."

#: auth/user_schema.py:25 auth/user_schema.py:140
msgid "No such user."
msgstr "Нет такого пользователя."

#: auth/user_schema.py:34
msgid "User name must contain minimum 3 characters. It must contain letters and digits, _, -, +."
msgstr "Имя пользователя должно содержать буквы, цифры, _, -, + и быть не короче 3 символов."

#: auth/user_schema.py:43
msgid "Email must contain English characters and/or digits, @ and domain name."
msgstr "Email должен содержать символы латинского алфавита и/или цифры, иметь @ и домен."

#: auth/user_schema.py:136
msgid "Scpecify id or username."
msgstr "Укажите ID или имя пользователя."

#: auth/utils/hashers.py:140
#, python-format
msgid "Couldn't load %r algorithm library: %s"
msgstr "Не может загрузиться %r библиотека алгоритмов: %s"

#: auth/utils/hashers.py:143
#, python-format
msgid "Hasher %r doesn't specify a library attribute"
msgstr "Hasher %r не указывает атрибут библиотеки."

#: auth/utils/hashers.py:152
msgid "Subclasses of BasePasswordHasher must provide a verify() method"
msgstr "Подклассы BasePasswordHasher должны предоставлять метод verify()."

#: auth/utils/hashers.py:161
msgid "Subclasses of BasePasswordHasher must provide an encode() method"
msgstr "Подклассы BasePasswordHasher должны предоставлять метод encode()."

#: auth/utils/hashers.py:186
msgid "Subclasses of BasePasswordHasher should provide a harden_runtime() method"
msgstr "Подклассы BasePasswordHasher должны предоставлять метод harden_runtime()."

#: auth/utils/veil_jwt.py:28
msgid "Token invalid."
msgstr "Недействительный токен."

#: auth/utils/veil_jwt.py:30
msgid "jwtauth: jwt.ExpiredSignature"
msgstr "jwtauth: jwt.ExpiredSignature"

#: auth/utils/veil_jwt.py:33
msgid "Token expired."
msgstr "Срок действия токена истек."

#: auth/utils/veil_jwt.py:36
msgid "jwtauth: Assertion error {}"
msgstr "jwtauth: ошибка утверждения {}."

#: auth/utils/veil_jwt.py:86
msgid "Error with JWT decode"
msgstr "Ошибка JWT декодирования."

#: auth/utils/veil_jwt.py:96 auth/utils/veil_jwt.py:98
#: auth/utils/veil_jwt.py:100
msgid "invalid header authorization"
msgstr "Недействительный заголовок авторизации."

#: auth/utils/veil_jwt.py:104
msgid "Missing Authorization header"
msgstr "Пропущен заголовок авторизации."

#: common/veil_client.py:48
msgid "jwt {}"
msgstr "jwt {}"

#: common/veil_client.py:78
msgid "Controller {} connection error"
msgstr "Ошибка подключения к контроллеру {}"

#: common/veil_client.py:83
#, python-brace-format
msgid "URL {url} - {http_error}"
msgstr "URL {url} - {http_error}"

#: common/veil_client.py:91
msgid "url: {} - {}"
msgstr "url: {} - {}"

#: common/veil_client.py:103
msgid "URL not found"
msgstr "URL не найден."

#: common/veil_client.py:121
msgid "Can't process Content-Type."
msgstr "Не может обработаться Content-Type."

#: common/veil_client.py:124
msgid "Only 'json' Content-Type."
msgstr "Content-Type только 'json'."

#: common/veil_decorators.py:28
msgid "Expect that 'body' is the 4 parameter in args. But in the same time 'body' in kwargs. Check it."
msgstr "Ожидается, что 'body' это 4 параметра в аргументах. Но в то же время 'body' в kwargs. Проверьте."

#: common/veil_decorators.py:62
msgid "Can check only kwargs or args. Not both at the same time."
msgstr "Можете проверить только kwargs или аргументы. Не оба обдовременно."

#: common/veil_decorators.py:67 common/veil_decorators.py:81
msgid "The parameters to be checked are in an dict. Can't explicitly match values with tuple."
msgstr "Параметры, которые нужно проверить, указаны в формате словаря. Значения не могут явно сопоставиться с кортежем."

#: common/veil_decorators.py:77
msgid "Value {} is invalid. Valid values are: {}"
msgstr "Значение {} неверно. Допустимые значения: {}"

#: common/veil_decorators.py:84
msgid "Parameter {} is necessary."
msgstr "Параметр {} необходим."

#: common/veil_decorators.py:89
msgid "Parameter {} value {} is invalid. Valid values are: {}"
msgstr "Параметр {} значения {} неверный. Допустимые значения: {}"

#: common/veil_decorators.py:119
msgid "IP: . username: {}"
msgstr "IP: . пользователь: {}"

#: common/veil_decorators.py:121
msgid "IP: {}. username: {}"
msgstr "IP: {}. Пользователь: {}."

#: common/veil_errors.py:123
msgid "Controller is not available."
msgstr "Контроллер недоступен."

#: common/veil_errors.py:140
msgid "Unable to logon to system using these credentials."
msgstr "Не удалось войти в систему с предоставленными учетными данными."

#: common/veil_errors.py:149
msgid "Critical controller error."
msgstr "Критическая ошибка контроллера."

#: common/veil_validators.py:32
msgid "Field \"{}\" - {}"
msgstr "Поле \"{}\" - {}"

#: controller/client.py:27
msgid "Auth failed."
msgstr "Ошибка авторизации."

#: controller/models.py:85 controller/models.py:119
msgid "No such controller"
msgstr "Нет такого контроллера."

#: controller/models.py:125 controller/models.py:140
msgid "Checking controller credentials: address: {}, username: {}, password: {}, ldap_connection: {}"
msgstr "Проверка учетных данных контроллера: адрес: {}, имя: {}, пароль: {}, ldap_connection: {}."

#: controller/models.py:131
msgid "Controller {} check failed."
msgstr "Проверка контроллера {} не удалась."

#: controller/models.py:132
msgid "Controller check: {}"
msgstr "Проверка контроллера: {}"

#: controller/models.py:134
msgid "Controller {} check passed successfull."
msgstr "Проверка контроллера {} прошла успешно."

#: controller/models.py:146
msgid "Get controller credentials: Controller's {} credentials are good."
msgstr "Получение учетных данных контроллера: Хорошие учетные данные контроллера {}."

#: controller/models.py:181
msgid "Can't connect to controller {} with username: {}, password: {}, ldap_connection: {}"
msgstr "Не подключается к контроллеру {} с именем: {}, паролем: {}, ldap_connection: {}."

#: controller/models.py:189
msgid "Can't login login to controller {}"
msgstr "Не получается войти на контроллер {}."

#: controller/models.py:191
msgid "Error with controller update: {}"
msgstr "Ошибка с обновлением контроллера {}."

#: controller/models.py:201
msgid "Controller has pool of virtual machines. Please completely remove."
msgstr "У контроллера есть пулы виртуальных машин. Выполните полное удаление."

#: controller/models.py:203
#, python-brace-format
msgid "Controller {name} had remove."
msgstr "Выполнено удаление контроллера {name}."

#: controller/models.py:217
#, python-brace-format
msgid "Controller {name} had completely remove."
msgstr "Выполнено полное удаление контроллера {name}."

#: controller/schema.py:73
msgid "Controller name cannot be empty."
msgstr "Имя контроллера не может быть пустым."

#: controller/schema.py:94
#, python-brace-format
msgid "Successfully added new controller {name} with address {address}."
msgstr "Успешно добавлен новый контроллер {name} с адресом {address}."

#: controller/schema.py:102
#, python-brace-format
msgid "Add new controller with address {address}: operation failed."
msgstr "Ошибка добавления нового контроллера с адресом {address}."

#: controller/schema.py:129 controller/schema.py:176 controller/schema.py:202
#: controller/schema.py:231
msgid "No such controller."
msgstr "Нет такого контроллера."

#: controller/schema.py:145
#, python-brace-format
msgid "Fail to update controller {id}: {error}"
msgstr "Ошибка обновления контроллера {id}: {error}"

#: controller/schema.py:154
#, python-brace-format
msgid "Successfully update controller {name} with address {address}."
msgstr "Успешно обновлен контроллер {name} с адресом {address}."

#: controller_resources/schema.py:321 controller_resources/schema.py:374
#: controller_resources/schema.py:423
msgid "The sort parameter is incorrect"
msgstr "Неверный параметр сортировки."

#: database.py:84
msgid "Incorrect sort parameter {}"
msgstr "Неверный параметр сортировки {}."

#: database.py:93
msgid "Incorrect request parameter {}"
msgstr "Неверный параметр запроса {}."

#: event/schema.py:147
msgid "No such event."
msgstr "Нет такого события."

#: event/schema.py:192
msgid "Journal is clear."
msgstr "Журнал очищен."

#: pool/models.py:141
msgid "Incorrect sorting option {}."
msgstr "Неверный параметр сортировки {}."

#: pool/models.py:355 pool/models.py:377
msgid "Pool already has permission."
msgstr "Пул уже имеет разрешение."

#: pool/models.py:399
msgid "Pool already has role."
msgstr "Пул уже имеет роль."

#: pool/models.py:432
msgid "Controller {} not found."
msgstr "Контроллер {} не найден."

#: pool/models.py:445
msgid "Pool has VMs. Please completely remove."
msgstr "У пула виртуальных машин есть виртуальные машины. Выполните полное удаление."

#: pool/models.py:448
#, python-brace-format
msgid "Removal pool of desktops {verbose_name} is done."
msgstr "Выполнено удаление пула рабочих столов {verbose_name}."

#: pool/models.py:522
msgid "Create Pool"
msgstr "Создание пула."

#: pool/models.py:529
msgid "Create StaticPool"
msgstr "Создание статического пула."

#: pool/models.py:630
msgid "Create Pool {}"
msgstr "Создание пула {}."

#: pool/models.py:637
msgid "Create AutomatedPool {}"
msgstr "Создание автоматического пула {}."

#: pool/models.py:668
msgid "Update Pool values for AutomatedPool {}"
msgstr "Обновление значений пула для автоматического пула {}."

#: pool/models.py:682
msgid "Update AutomatedPool values for {}"
msgstr "Обновление значений автоматического пула для {}."

#: pool/models.py:709
msgid "add_domain {}, attempt № {}, of {}"
msgstr "Добавление домена {}, попытка № {} из {}."

#: pool/models.py:713
msgid "VM creation task id: {}"
msgstr "ID задачи создания виртуальной машины: {}."

#: pool/models.py:717
msgid "Fail to create VM on ECP. Re-run."
msgstr "Ошибка создания виртуальной машины на ECP. Перезапустите."

#: pool/models.py:723
msgid "Subscribe to ws messages."
msgstr "Подпишитесь на сообщения ws."

#: pool/models.py:728
msgid "Wait for result."
msgstr "Ожидайте результата."

#: pool/models.py:734
msgid "Create virtual machine"
msgstr "Создание виртуальной машины."

#: pool/models.py:767
msgid "Could not get the response about result of creation VM on ECP by WS. Task status check."
msgstr "Не удалось получить ответ о результате создания ВМ на ECP по WS. Проверим статус задачи."

#: pool/models.py:771
msgid "Probably task is not done. Check VM status."
msgstr "Вероятно, задание не выполнено. Проверьте состояние ВМ."

#: pool/models.py:796
msgid "Error with create VM {} was {} times."
msgstr "Ошибка с созданием виртуальной машины {} была {} раз."

#: pool/models.py:808
msgid "Add {} initial vms for pool {}. Controller address: {}"
msgstr "Добавление {} начальных виртуальных машин для пула {}. Адрес контроллера: {}."

#: pool/models.py:815
msgid "Pool {} os type is: {}"
msgstr "Операционная система пула {}: {}."

#: pool/models.py:818
msgid "Automated pool creation started"
msgstr "Автоматическое создание пула началось."

#: pool/models.py:829
msgid "Automated pool creation. Created {} VMs from {}"
msgstr "Автоматическое создание пула. Создание {} виртуальных машин из {}."

#: pool/models.py:846
msgid "Can't create VM:"
msgstr "Невозможно создать виртуальную машину:"

#: pool/models.py:848
msgid "Can't create VM"
msgstr "Невозможно создать виртуальную машину."

#: pool/models.py:854
msgid "Automated pool successfully created. Initial VM amount {}"
msgstr "Автоматический пул успешно создан. Начальное количество виртуальных машин {}"

#: pool/models.py:857
msgid "Automated pool created with errors. VMs created: {}. Required: {}"
msgstr "Автоматический пул создан с ошибками. Созданные виртуальные машины: {}. Необходимо: {}."

#: pool/models.py:874
msgid "Could not create the required number of machines."
msgstr "Не удалось создать необходимое количество машин."

#: pool/models.py:923
msgid "VM creating error:"
msgstr "Ошибка создания виртуальной машины:"

#: pool/models.py:929
msgid "Delete VMs for AutomatedPool {}"
msgstr "Удаление виртуальных машин для автоматического пула {}."

#: pool/models.py:932
msgid "Calling soft delete for vm {}"
msgstr "Вызов мягкого удаления для виртуальной машины {}"

#: pool/pool_task_manager.py:70
msgid "Logic error: no such pool"
msgstr "Логическая ошибка: нет такого пула."

#: pool/schema.py:57 pool/schema.py:354 pool/schema.py:381
msgid "No such pool."
msgstr "Нет такого пула."

#: pool/schema.py:69
msgid "ip-address probably invalid."
msgstr "Возможно, неверный IP адрес."

#: pool/schema.py:79
msgid "Pool name must contain only characters, digits, _, -"
msgstr "Имя пула должно содержать только буквы, цифры, _, -."

#: pool/schema.py:90
msgid "Template name of VM must contain only characters, digits, _, -"
msgstr "Шаблонное имя вм должно содержать только буквы, цифры, _, -"

#: pool/schema.py:98
msgid "Initial number of VM must be in {}-{} interval"
msgstr "Начальное число виртуальных машин должно быть в интервале {}-{}."

#: pool/schema.py:115
msgid "Number of created VM must be in {}-{} interval"
msgstr "Число создаваемых виртуальных машин должно быть в интервале {}-{}."

#: pool/schema.py:136 pool/schema.py:704
msgid "Maximal number of created VM should be less than initial number of VM"
msgstr "Максимальное число создаваемых виртуальных машин не должно быть меньше начального числа ВМ."

#: pool/schema.py:138 pool/schema.py:706
msgid "Maximal number of created VM must be in [{} {}] interval"
msgstr "Максимальное число создаваемых виртуальных машин должно быть в интервале [{} {}]."

#: pool/schema.py:432
msgid "HttpError: {}"
msgstr "Ошибка Http: {}"

#: pool/schema.py:442
msgid "VM with id {} not found in any controllers"
msgstr "Виртуальная машина с {} ID не найдена ни на одном из известных контроллеров."

#: pool/schema.py:453
msgid "StaticPool: Get vm info"
msgstr "Статический пул: получение информации о ВМ."

#: pool/schema.py:456
msgid "StaticPool: Check that all vms are on the same node"
msgstr "Статический пул: Убедитесь, что все виртуальные машины находятся на одном узле."

#: pool/schema.py:461
msgid "All of VM must be at one server"
msgstr "Все виртуальные машины должны быть на одном сервере."

#: pool/schema.py:468
msgid "StaticPool: Determine cluster"
msgstr "Статический пул: Определение кластера"

#: pool/schema.py:473 pool/schema.py:485
msgid "StaticPool: Determine datapool"
msgstr "Статический пул: Определение пула данных."

#: pool/schema.py:492
msgid "StaticPool: Objects on VDI DB created."
msgstr "Статический пул: объекты на VDI DB созданы."

#: pool/schema.py:495
msgid "VM info {}"
msgstr "Информация о ВМ {}"

#: pool/schema.py:506
msgid "StaticPool: pool {} created."
msgstr "Статический пул: пул {} создан."

#: pool/schema.py:507
#, python-brace-format
msgid "Static pool {name} created."
msgstr "Статический пул {name} создан."

#: pool/schema.py:509 pool/schema.py:511
msgid "Failed to create static pool {}."
msgstr "Ошибка создания статического пула {}."

#: pool/schema.py:531 pool/schema.py:583
msgid "List of VM should not be empty"
msgstr "Список виртуальных машин не должен быть пустым."

#: pool/schema.py:544
msgid "VM ids: {}"
msgstr "ID виртуальных машин: {}"

#: pool/schema.py:549
msgid "VM {} is at server different from pool server now"
msgstr "ВМ {} находится на сервере отличном от сервера пула."

#: pool/schema.py:552
msgid "VM {} is already in one of pools"
msgstr "Виртуальная машина {} уже в одном из пулов."

#: pool/schema.py:557
msgid "All VMs on node: {}"
msgstr "Все виртуальные машины на узле: {}."

#: pool/schema.py:592
msgid "VM doesn't belong to specified pool"
msgstr "Виртуальная машина не принадлежит заданному пулу."

#: pool/schema.py:655
msgid "Failed to create automated pool {}."
msgstr "Ошибка создания автоматического пула {}."

#: pool/schema.py:709
msgid "Maximal number of created VM can not be reduced."
msgstr "Максимальное количество создаваемых виртуальных машин не может быть уменьшено."

#: pool/schema.py:725
#, python-brace-format
msgid "Automated pool {name} updated."
msgstr "Автоматический пул {name} обновлен."

#: pool/schema.py:727
msgid "Automated pool {} updated."
msgstr "Автоматический пул {} обновлен."

#: resources_monitoring/handlers.py:79
msgid "destructor VdiFrontWsHandler"
msgstr "Деструктор VdiFrontWsHandler"

#: resources_monitoring/handlers.py:92
msgid "Message: "
msgstr "Сообщение: "

#: resources_monitoring/handlers.py:105
msgid "Unknown subscription source"
msgstr "Неизвестный источник подписки."

#: resources_monitoring/handlers.py:116
msgid "already subscribed"
msgstr "уже подписан"

#: resources_monitoring/handlers.py:120
msgid "not subscribed"
msgstr "не подписан"

#: resources_monitoring/handlers.py:131
msgid "WebSocket closed"
msgstr "WebSocket закрыт."

#: resources_monitoring/handlers.py:163
msgid "Write error"
msgstr "Ошибка записи."

#: resources_monitoring/resources_monitor.py:107
msgid "{} is connected {}"
msgstr "{} подключен к {}."

#: resources_monitoring/resources_monitor.py:140
#, python-brace-format
msgid "{cls}: an not connect to {ip}"
msgstr "{cls}: не подключен к {ip}."

#: resources_monitoring/resources_monitor.py:149
msgid "add {}"
msgstr "добавление {}."

#: resources_monitoring/resources_monitor.py:170
msgid "{} Closing ws connection {}"
msgstr "{} Закрытие ws соединения {}."

#: resources_monitoring/resources_monitor_manager.py:30
#, python-brace-format
msgid "{cls}: connected controllers -- {controllers}"
msgstr "{cls}: подключенные контроллеры -- {controllers}."

#: resources_monitoring/resources_monitor_manager.py:39
msgid "{}: Started"
msgstr "{}: Запущен."

#: resources_monitoring/resources_monitor_manager.py:74
#, python-brace-format
msgid "{cls}: Controller {ip} is already monitored!"
msgstr "{cls}: Контроллер {ip} уже отслеживается!"

#: resources_monitoring/resources_monitor_manager.py:81
#, python-brace-format
msgid "{cls}: resource monitor for controller {ip} connected"
msgstr "{cls}: монитор ресурсов для контроллера {ip} подключен."

#: resources_monitoring/resources_monitor_manager.py:92
#, python-brace-format
msgid "{cls}: controller {ip} is not monitored!"
msgstr "{cls}: контроллер {ip} не отслеживается!"

#: resources_monitoring/resources_monitor_manager.py:100
#, python-brace-format
msgid "{cls}: resource monitor for controller {ip} removed"
msgstr "{cls}: удален монитор ресурсов для контроллера {ip}."

#: thin_client_api/handlers.py:48
msgid "Pool not found."
msgstr "Пул не найден."

#: thin_client_api/handlers.py:59
msgid "User does not have permission to use pool."
msgstr "Пользователь не имеет разрешения на использование пула."

#: thin_client_api/handlers.py:92
msgid "Pool has not free machines"
msgstr "В пуле нет свободных машин"

#: thin_client_api/handlers.py:119
msgid "VM does not support RDP"
msgstr "Виртуальная машина не поддерживает RDP."

#: thin_client_api/handlers.py:142
msgid "User {} not found."
msgstr "Пользователь {} не найден."

#: thin_client_api/handlers.py:145
msgid "There is no pool with id: {}"
msgstr "Отсутствует пул с ID: {}."

#: thin_client_api/handlers.py:149
msgid "User {} has no VM on pool {}"
msgstr "У пользователя {} нет виртуальной машины в пуле {}"

#: vm/models.py:79
msgid "Create VM {} on VDI DB."
msgstr "Создание виртуальной машины {} на VDI DB."

#: vm/models.py:100
msgid "Fail to remove VM {} from ECP: "
msgstr "Ошибка удаления ВМ {} из ECP."

#: vm/models.py:101
msgid "Vm {} removed from ECP."
msgstr "ВМ {} удалена из ECP."

#: vm/models.py:113
msgid "Vm already has permission."
msgstr "Вм уже имеет разрешение."

#: vm/models.py:172
msgid "Trying to create VM on ECP with verbose_name={}"
msgstr "Попытка создать виртуальную машину на ECP с verbose_name = {}"

#: vm/models.py:178
msgid "Request to create VM sent without surprise. Leaving while."
msgstr "Запрос на создание ВМ отправлен без неожиданностей. Покидаем while."

#: vm/models.py:185
msgid "ECP error: {}"
msgstr "Ошибка ECP: {}"

#: vm/models.py:187
msgid "Bad domain name {}"
msgstr "Неверное доменное имя {}"

#: vm/models.py:192
msgid "Controller has not free space for creating new VM."
msgstr "На контроллере отсутствует место для создания новой виртуальной машины."

#: vm/models.py:193
msgid "Not enough free space on data pool"
msgstr "Недостаточно свободного места в пуле данных."

#: vm/models.py:197
msgid "Possibly blocked by active task on ECP. Wait before next try."
msgstr "Возможно, заблокировано активным заданием на ECP. Подождите перед следующей попыткой."

#: vm/models.py:200
msgid "Something went wrong. Interrupt while."
msgstr "Что-то пошло не так. Прерываем while."

#: vm/models.py:204
msgid "Wait one more try"
msgstr "Подождите еще одну попытку."

#: vm/schema.py:158
msgid "There is no VM {}"
msgstr "Нет ВМ {}."

#: vm/schema.py:174
msgid "User does not have the right to use pool, which has VM."
msgstr "У пользователя нет прав на использование пула, которому принадлежит VM."

#: vm/schema.py:216
msgid "GraphQL: Resolving template info"
msgstr "GraphQL: разрешение информации о шаблоне."

#: vm/schema.py:221
msgid "Template data could not be retrieved: {}"
msgstr "Не удалось получить данные Шаблона: {}"

#: vm/schema.py:231
msgid "VM data could not be retrieved: {}"
msgstr "Не удалось получить данные виртуальной машины: {}"

#: vm/schema.py:242
msgid "Templates list could not be retrieved: {}"
msgstr "Не удалось получить список шаблонов: {}"

#: vm/schema.py:278 vm/schema.py:356
msgid "Incorrect sort parameter"
msgstr "Неверный параметр сортировки."

#: vm/schema.py:286
msgid "GraphQL: Resolving VMs"
msgstr "GraphQL: разрешение виртуальных машин."

#: vm/schema.py:293
msgid "VMs list could not be retrieved: {}"
msgstr "Не удалось получить список виртуальных машин: {}"

#: vm/schema.py:298
msgid "GraphQL: VM type list:"
msgstr "GraphQL: список типов виртуальных машин:"

#, fuzzy
#~ msgid "Parameter action value {} is invalid"
#~ msgstr "Параметр action значения {} неверный"
